### ISSUE TITLE
nav bar partially updating

### ISSUE THREAD

**Issue by jkarimi91** [dunovank/jupyter-themes#10]
the nav bar partially maintains a white background still.
<img width="1217" alt="screen shot 2016-01-19 at 10 42 22 pm" src="https://cloud.githubusercontent.com/assets/8411317/12441648/1ea5ba78-befe-11e5-9844-3737b11875de.png">

**Comment by dunovank** [comment]
hmm... I'm not able to recreate this. The navbar toggle (-T) still seems to be broken in the latest version. I will try to get to this when I have a moment but I'm pretty swamped at work right now. Are you able to toggle off the navbar (see instructions at bottom of readme)? Is there still extra white space on the periphery of the menubar (File, Edit, View, etc...)?   Also, could you give me some info about your system, browser, etc.?

Best,
kd

**Comment by dunovank** [comment]
Happened to me after upgrading to notebook 4.1 

Should be fixed now. Closing this issue.
