### ISSUE TITLE
Why isn't there an option to set cursor color to white?

### ISSUE THREAD

**Issue by jingw222** [dunovank/jupyter-themes#107]

**Comment by dunovank** [comment]
In the next release you'll be able to set the cursor color to the same color as the code cell font with the argument `-cursc x`

**Comment by jingw222** [comment]
Thank you very much for your great contributions. One thing that's baffling is that when I set the cursor width to 8 ( like a block shape), the cursor somehow covers the code in that block. Any idea how to deal with this kind of issue? 

BTW I don't know why I don't see the `out[]` indicators. lol
