### ISSUE TITLE
Styling the background color of particular md or code cells

### ISSUE THREAD

**Issue by psychemedia** [dunovank/jupyter-themes#108]
Is there any way of supporting different background colours for code and markdown cells that are tagged with a particular metadata field?

For example, in an old notebook config I've been using for a couple of years, we were theming particular cells as follows:

![pasted_image_29_03_2017_22_18](https://cloud.githubusercontent.com/assets/82988/24477106/b3fe8b92-14cd-11e7-96fa-e4f2b464954d.png)

Looking at the new notebooks, I can't see a quick way in to setting a single class attribute on (part of) a cell that a simple css file will pick up, which is the solution I was using before (set class attribute via an extension based on cell metadata).

**Comment by dunovank** [comment]
Hey sorry about the delayed response. I don't have any experience with metadata tags for cells, didn't actually know this was possible. I'll definitely look into this though, seems like it'd be super useful for instructional exercises, tutorials, etc. Any tips or suggestions you might have are certainly welcomed, and obviously feel free to submit a PR if you end up putting something together. Will post any progress updates here.

**Comment by arnavs** [comment]
Just wanted to check---is there any current solution for this? (render cells differently based on a cell tag or METADATA).

I'm running into exactly the same issue but there doesn't seem to be an existing solution...
