### ISSUE TITLE
Plot axes ticks, labels, and titles don't show since last update

### ISSUE THREAD

**Issue by jingw222** [dunovank/jupyter-themes#113]
`jtplot.style()` doesn't do the trick also. Am I doing something wrong?

**Comment by dunovank** [comment]
Hmm... weird. Could you post a screen shot?

**Comment by jingw222** [comment]
![nolabel](https://cloud.githubusercontent.com/assets/5494367/25208998/bcbc90ec-25aa-11e7-80f8-67b030c1c86d.png)

**Comment by dunovank** [comment]
hmmm... what theme are you using?

**Comment by dunovank** [comment]
can you try running` jtplot.style('grade3')`

**Comment by dunovank** [comment]
or `jtplot.style('onedork')

**Comment by jingw222** [comment]
It works now somehow. Thanks for your help!

**Comment by dunovank** [comment]
good deal.
