### ISSUE TITLE
Remove theme

### ISSUE THREAD

**Issue by hugo-pires** [dunovank/jupyter-themes#114]
Hello
I am trying to remove Jupyter Themes. I've already uninstalled, emptied cache, restart server and browser. Not working...

Could you help me?

Thank you

**Comment by dunovank** [comment]
did you run `jt -r` before uninstalling jupyterthemes? If not, try reinstalling (`pip install jupyterthemes`) then running `jt -r` then uninstalling again with pip. Alternatively you could try manually deleting any leftover files by running the following commands in your terminal:
```sh
rm ~/.jupyter/custom/current_theme.txt
rm ~/.jupyter/custom/custom.css
rm -rf ~/.jupyter/custom/fonts
```

**Comment by hugo-pires** [comment]
Done. Thank you.
