### ISSUE TITLE
Increasing cell-width to full screen

### ISSUE THREAD

**Issue by vgoklani** [dunovank/jupyter-themes#116]
Would it be possible to automatically incorporate the solution from this:

http://stackoverflow.com/questions/21971449/how-do-i-increase-the-cell-width-of-the-jupyter-ipython-notebook-in-my-browser

into this project?

**Comment by dunovank** [comment]
You should be able to do this with the `-cellw` CL argument (e.g., `jt -t onedork -cellw 100%`)

is that what you're looking for?

**Comment by vgoklani** [comment]
yes! thanks: 

    jt -t oceans16 -f roboto -fs 12 -cellw 100%

it wasn't obvious from the README.md. It would help adding that one additional example

**Comment by xuzhang5788** [comment]
I don't like the dark background. I only want to increase the width of the cell to 100%. When I used jt -cellw 100%, it didn't work. I changed 100% to 2000, still didn't work.

**Comment by xuzhang5788** [comment]
When I used the light color which you suggested, my head of output was cut a little bit. Such as "training", only display like "raining"

**Comment by tdiethe** [comment]
> When I used the light color which you suggested, my head of output was cut a little bit. Such as "training", only display like "raining"

Did you find a solution to this? I have the same issue:

![image](https://user-images.githubusercontent.com/1110560/45682173-7b3d2400-bb37-11e8-956a-4f3795f91276.png)

**Comment by tdiethe** [comment]
Discovered this has already been opened #273 

> > When I used the light color which you suggested, my head of output was cut a little bit. Such as "training", only display like "raining"
> 
> Did you find a solution to this? I have the same issue:
> 
> ![image](https://user-images.githubusercontent.com/1110560/45682173-7b3d2400-bb37-11e8-956a-4f3795f91276.png)
