### ISSUE TITLE
Different appearance on oceans16 theme in README and real workspace

### ISSUE THREAD

**Issue by dyzdyz010** [dunovank/jupyter-themes#123]
## Screenshot in README

![oceans16_code_headers](https://cloud.githubusercontent.com/assets/1324420/25854170/b1d9d124-3501-11e7-84a9-adfe21471d7d.png)

## Screenshot in my notebook

![qq 20170509215000](https://cloud.githubusercontent.com/assets/1324420/25854234/e4ef53a4-3501-11e7-9d75-1d10d5ae6a34.png)

Colors in markdown cell are not the same

Theme flushed no cache issues.

**Comment by dunovank** [comment]
Yeah, I've added a comment about this to the readme. The screenshots are of an older version, the one you're seeing is the updated version (slightly different style for command/edit mode of selected cell, header colors etc.). I'll update the screenshots when I have a free minute.
