### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by jingw222** [dunovank/jupyter-themes#124]
Could be a noob issue, but how to change the font size of a printed pandas dataframe or other printed texts? Tweaking `-tfs` and `-nfs` doesn't seem to be working for me.

**Comment by dunovank** [comment]
I've added two command line options to the latest release (v0.16.1) for setting output (general) and dataframe fontsizes.
```sh
# set output fontsize to 11pt and pandas df fontsize to 9pt (df header fontsize = dfs+1)
jt -t onedork -ofs 11 -dfs 9
```

**Comment by jingw222** [comment]
@dunovank wow! Nicely done! I'm impressed. ;)

**Comment by dunovank** [comment]
good deal!

**Comment by RJaikanth** [comment]
Hi @dunovank is there anyway I only change the fontsize and not the theme. I like the original theme
