### ISSUE TITLE
Not changing theme

### ISSUE THREAD

**Issue by Brett99** [dunovank/jupyter-themes#125]
Hello, I installed it with pip. 

After running "sudo jt -t chesterish", I open a new notebook and it looks the same as before.

**Comment by ddulic** [comment]
Did you restart the service?

**Comment by Brett99** [comment]
Sorry, but how do I restart it?

**Comment by ddulic** [comment]
Depends on how you started jupyter in the first time. In any case, it needs a restart before a theme in applied.

**Comment by dunovank** [comment]
Have you tried installing without sudo? Try `jt -t chesterish` then refresh the jupyter notebook window in your browser to see if theme installled correctly.

**Comment by Brett99** [comment]
I have tried this.

**Comment by dunovank** [comment]
From the **README**:
* **refreshing / removing / resetting:** depending on your system, browser, etc., you may need to empty your browser cache after installing a new theme (`-t`) or attempting to restore the default (`-r`) in order for those changes to take effect. (see discussion [here](https://github.com/dunovank/jupyter-themes/issues/86)). At the very least you'll need to refresh your browser window (usually `cmd+r` or `ctrl+r`). 

@Brett99 does this resolve your issue

**Comment by dunovank** [comment]
Going to close this since seems to be resolved.
