### ISSUE TITLE
Python installed with anaconda

### ISSUE THREAD

**Issue by FranekW** [dunovank/jupyter-themes#127]
I am not sure how to install this in my system. I am certain it could be a trivial question but I have just started with Python and everything is new.

I work on CentOS 7 and there are default python binaries installed in the system, which is Python 2.7.5. I read I should not remove it or mess up with it as the system still operates on python 2. Therefore, I left a default access to system python untouched. If I type Python in terminal, I get Python 2.7.5.

However, I installed a separate version of Python, 3.6.0, from Anaconda3 in totally different folder (/opt/anaconda3/bin) and only use this version. Jupyter and Spyder both recognise my custom installation (Python 3.6.0).

How should I proceed to correctly install your tool in CentOS 7?

Thanks

**Comment by avishapiro** [comment]
What happened when you tried the `pip` command in the instructions? Some more info might help. What do you get running `which python`? How do you start a jupyter notebook on your system?
