### ISSUE TITLE
Enabling ligatures in FiraCode

### ISSUE THREAD

**Issue by danielhauagge** [dunovank/jupyter-themes#130]
Is there a way to enable ligatures? I managed to get it working without this project using this gist
https://gist.github.com/mutsune/14bb6bb34679f04b76dba2de6e0f3549

**Comment by dunovank** [comment]
you can manually add those lines to the `~/.jupyter/custom/custom.css` file after installing your theme.

**Comment by xgdgsc** [comment]
Where to add those lines for now? I tried adding those lines in various locations in the file after setting theme with `jt -t monokai -f fira -fs 12` but still ligatures is not enabled.
