### ISSUE TITLE
Is there a way to get it to work with RISE?

### ISSUE THREAD

**Issue by zahachtah** [dunovank/jupyter-themes#131]
Rise is a slide presentation framework for Jupiter I use allt. after installing the themes its gone and reinstalling it does not bring it back. 

[RISE](https://github.com/damianavila/RISE)

Is it possible to have both? anyone know how that could be done?

**Comment by dunovank** [comment]
Hmmm... sorry to hear that. Are you able to recover full RISE functionality by uninstalling jupyterthemes? I'm not sure as I'm not familiar with RISE, but PR's are always welcome if anyone figures out how to make them play nice together.

**Comment by zahachtah** [comment]
was my bad, there are several ways of installing RISE, one did work. thanks for responding!
