### ISSUE TITLE
Not Reloading

### ISSUE THREAD

**Issue by wassimseif** [dunovank/jupyter-themes#132]
I have jupyter running off a docker container. i tried `jt -t onedork -f roboto -fs 12`. reload the page on chrome but nothing changed. i tried restarting the server. still nothing. just the default theme

**Comment by dunovank** [comment]
Hmm.. not sure. Maybe a docker compatibility issue? You're running jupyter notebook (not jupyter lab) correct? And get no errors when running the above command? Have you tried refreshing your browser cache? Just shooting from the hip here...

**Comment by wassimseif** [comment]
Yes I have tried refreshing the cache. most probably it's a docker issue. Just thought you have a fix for it

**Comment by dunovank** [comment]
Sorry I haven't ventured into working with docker yet so probably won't be of much help. You may have to include the package in docker? (excuse that answer if that literally makes no sense haha)

**Comment by wassimseif** [comment]
Haha
yeah i ssh'd into the container and installed it. 
you really should learn how to use docker. it's so helpful

**Comment by dunovank** [comment]
yeah I've been meaning to, haven't gotten around to it. So did that work or are you saying that's what you did before?

**Comment by wassimseif** [comment]
I didn't work in docker. i installed jupyter on my mac natively and then installed jupyterthemes and it worked normally

**Comment by ArVar** [comment]
For me, the only option was to restart the Docker container. But then it worked like a charm.

**Comment by kathirveltce** [comment]
Yeah! Its working..I put a command in jupyter notebook like `os.system('jt -t onedork')`. Because While building docker file it will create a new shell and set the corresponding jupyterthemes..

**Comment by spothapragada** [comment]
> Yeah! Its working..I added a nasty hack in jupyter_notebook_config.py - `os.system('jt -t onedork')`. Because docker creates a new shell and sets the corresponding jupyterthemes..

@kathirveltce Can you share the line where you set this in your ` jupyter_notebook_config.py` ?
