### ISSUE TITLE
How to change primary color in monokai

### ISSUE THREAD

**Issue by jingw222** [dunovank/jupyter-themes#133]
Maybe I'm nitpicking but is there a way to tilt the background color of cells a bit darker since I find the comments a bit illegible due to lower contrast? 
Now:
![temp2](https://cloud.githubusercontent.com/assets/5494367/26276348/4fabff4a-3da8-11e7-89bf-b8f531a0a0da.png)
Compared to this one:
![temp01](https://cloud.githubusercontent.com/assets/5494367/26276364/ab1d220a-3da8-11e7-8a22-94e50dc93ea5.png)
Any thoughts?

**Comment by dunovank** [comment]
Go to <path/to/site-packages/>jupyterthemes/styles/monokai.less 

if you want to change the comment color, find the line below and replace the hex color with something like #75715E (this will be the new comment color in the next release)
```less
@cm-comment:            #49483E;
```

or if you want to change the cell background find and modify this line
```less
@cc-input-bg:           #282828;
```

**Comment by jingw222** [comment]
Great. Glad to know that. Didn't know themes were this customizable. :+1:

**Comment by dunovank** [comment]
Yup, feel free to submit a PR with any cool custom themes you come up with!
