### ISSUE TITLE
May as well be able to change font without setting the theme

### ISSUE THREAD

**Issue by veritas718** [dunovank/jupyter-themes#135]
![image](https://cloud.githubusercontent.com/assets/677759/26498679/d1eb81c0-41fd-11e7-9a0e-bde00946736e.png)
If a user did have a lot of custom stuff, they should probably be able to change just the font without affecting anything else. 

thanks for adding hasklig ;)

**Comment by dunovank** [comment]
you should be able to do this in your browser. firefox, chrome, vivaldi (and I believe safari) allow you to specify the monospace font family and size. No prob!
