### ISSUE TITLE
Possibility to change the font size for menu bar

### ISSUE THREAD

**Issue by pkozela** [dunovank/jupyter-themes#137]
Is this possible ? 

Also, it would be nice to be able to completely hide the menu bar

**Comment by dunovank** [comment]
future releases will allow you to set the notebook fontsize with the -nfs flag
jt -t onedork -nfs 7

When I have some extra time I'll try adding an option to hide the menubar. In the meantime you might check out the [nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) library. There's an extension that allows you to hide the header etc (toolbar, menubar, navbar, etc) with a keyboard shortcut (called Hide Header)

**Comment by dunovank** [comment]
You can now change menubar fontsize with `-nfs` argument
`jt -t onedork -nfs 15`
