### ISSUE TITLE
How to change the line space?

### ISSUE THREAD

**Issue by TianbiaoHe** [dunovank/jupyter-themes#138]
Hi, first of all, I would like to thank for the author. The jupyter themes are awesome. 
But when I use the theme called "onedork", the line space between two lines are too close, it is not good for viewing the code. I don't know how to change the line space, please kindly tell me how to change the line space. Many thanks!

**Comment by dunovank** [comment]
I'll add a command line option for setting line height in the next release. Thanks!

**Comment by dunovank** [comment]
can now be set with `-lineh` argument

From the **README** examples
```sh
# adjust cell width (% screen width) and line height
jt -t chesterish -cellw 90% -lineh 170
```

**Comment by lisekarimi** [comment]
Is it feasible to replicate this functionality for Markdown cells, given that the current option does not influence them?
