### ISSUE TITLE
Adjustable font size for code area?

### ISSUE THREAD

**Issue by auselen** [dunovank/jupyter-themes#14]
Default font size is too big for my setup. Is it possible to make it configurable from command-line?

**Comment by dunovank** [comment]
Sorry about the font size issue. Is it just the code cell font-size? Or also on the startup page/menubar/dropdown menus/etc? I think this would be a very useful feature so I will try to add this capability as soon asap. 
kd

**Comment by auselen** [comment]
Code size was the issue for me.

Is it possible to make cells bigger as well? like removing most of the padding on the sides?

**Comment by dunovank** [comment]
Yes this is definitely possible. To be honest, the css files are a bit of a mess to say the least so once I have an opening in my schedule I'm going spend a day cleaning things up and commenting. That way adding a bit more CL flexibility for fontsize, cell width, etc should be a lot less painful.

**Comment by auselen** [comment]
Cool!

**Comment by dunovank** [comment]
I've made an attempt at including a CL argument for customizing the font-size within code cells (see updated install instructions on the home page README). I won't close this issue just yet as I've only done minimal testing on my linux machine.

**Comment by auselen** [comment]
font sized work for me too. next step is cell size?

**Comment by dunovank** [comment]
Good suggestion. Closing this now.
