### ISSUE TITLE
the run button and other button disappear

### ISSUE THREAD

**Issue by denotepython** [dunovank/jupyter-themes#140]
there is a set of button to click “run”，“up”，“down”and so on in the bottom of taskbar "file" "edit"...but when  I install this theme,these button disappear, picture can  describe my meaning better, but can't upload picture. i don’t know whether you understand my question.

**Comment by dunovank** [comment]
I think you're referring to the toolbar. You can use the -T flag when installing your theme to toggle this on.
Example:
```sh
jt -t oceans16 -T
```

**Comment by denotepython** [comment]
@dunovank thank you ,it works!
