### ISSUE TITLE
Provide minimum versions for your requirements

### ISSUE THREAD

**Issue by LLrsokl** [dunovank/jupyter-themes#142]
pip-installing jupyter-themes force-installs the latest release for packages like seaborn, which force-installs the latest version of numpy. 

For anaconda users, this can overwrite the mkl-optimized numpy package, and can lead to side-by-side versions of conda ipython and pip ipython.

This can be remedied by specifying minimum required versions for the packages.

**Comment by dunovank** [comment]
Ah, thanks @LLrsokl . I'll be sure to include minimum versions in the next release. Thanks for the heads up.

**Comment by LLrsokl** [comment]
I'm bugging the guys at `seaborn` too ;)

Loved the themed-plots, by the way!

**Comment by dunovank** [comment]
Added the same "fix" as the seaborn guys (only installs dependencies that are not already installed so as to prevent unnecessary forced upgrades)
