### ISSUE TITLE
R Documentation in Jupyter looks weird

### ISSUE THREAD

**Issue by jingw222** [dunovank/jupyter-themes#145]
![temp_r](https://user-images.githubusercontent.com/5494367/27618690-66a88950-5bf0-11e7-881e-d8106deb9079.png)

It's fine with Python Kernel though. Any ideas?

**Comment by dunovank** [comment]
@jingw222 can you try running `pip install --upgrade jupyterthemes` to see if the issue is fixed?

**Comment by jingw222** [comment]
Thanks! I can't appreciate enough all of your dedicated work on this awesome project.

**Comment by dunovank** [comment]
Thanks for the kind words @jingw222 ! I assume this issue can be closed then?

**Comment by jingw222** [comment]
Yes, please close it as it's not relevant any more. :)

**Comment by dunovank** [comment]
Cool, thanks!
