### ISSUE TITLE
doesn't look like what I expected

### ISSUE THREAD

**Issue by suzirui123** [dunovank/jupyter-themes#146]
hi there, I just install jupyterthemes on my new PC, however I found only layout changes, font seems to be the same
what I see:
![image](https://user-images.githubusercontent.com/15870579/27667960-c31d7fb8-5cb0-11e7-9735-e5b5e50ac440.png)
what I expect:
![image](https://user-images.githubusercontent.com/15870579/27667977-d7f953da-5cb0-11e7-9401-c665d9bef1b9.png)
I wonder why, thx!

**Comment by dunovank** [comment]
Some of the styling has changed since those screenshots were created. You can try updating to the latest version, i've changed some stylistic stuff.
