### ISSUE TITLE
White Header in Theme solarizedl

### ISSUE THREAD

**Issue by xwjabc** [dunovank/jupyter-themes#148]
<img width="1124" alt="solarizedl-white-header" src="https://user-images.githubusercontent.com/16413829/27980316-29fa49aa-6332-11e7-8482-8265300f31c6.png">

@dunovank  It seems the color of the header is white. Is there any way to change the color and make it the same as the background color?

My configuration is:
`jt -t solarizedl -f inconsolata -fs 95 -tfs 9 -nfs 115 -cellw 88% -lineh 140`

**Comment by xwjabc** [comment]
<img width="1253" alt="solarizedl-white-header-fixed" src="https://user-images.githubusercontent.com/16413829/27982099-e261b2be-634e-11e7-9e5f-7667f288dece.png">

Finally I have solved it. At the end of `/layout/notebook.less`, I add 
```
#button-select-all {
    background-color: @form-input-bg !important;
}

#tree-selector-btn {
    background-color: @form-input-bg !important;
}
```
Besides, in `/styles/solarizedl.less` I change the  `@form-input-bg:         #ffffff;` into `@form-input-bg:         #e7dec3;`.
Though it may change the background color of input space, I can accept it.

**Comment by dunovank** [comment]
This should be fixed in the latest version 

```
pip install --upgrade jupyterthemes
```
