### ISSUE TITLE
MOAR THEMEZ

### ISSUE THREAD

**Issue by parenthetical-e** [dunovank/jupyter-themes#15]
There are many here

https://github.com/merqurio/jupyter_themes/tree/master/themes

add 'em?

(Also, awesome work with this Kyle!)

**Comment by dunovank** [comment]
Yeah I've chatted with him briefly, would definitely love to integrate all
those syntax themes with the general notebook design of the oceans16/grade3
themes. The css is still a bit of a mess on my end though, would take a
fair bit of refactoring. Someday.

and thanks dude! Lets skype soon yeah? I'm sure we both have mutually
interesting updates to share.

On Sunday, February 14, 2016, Erik <notifications@github.com> wrote:
> There are many here
>
> https://github.com/merqurio/jupyter_themes/tree/master/themes
>
> add 'em?
>
> (Also, awesome work with this Kyle!)
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/acxkWjvoHTzc69FCRT52PsUEGLe90XGMYBzfsdVJvtuG-KBvbrqQdHDluwPjxXFXlyZEE7lZ1mLLkUSVs3Y7quocDZUvMrE9BtmH34Xrk0TqUjKBRsH-JPLwK9og9lvS2Fg-eItejnFgveV2fmgeGnTjc4lQBw=s0-d-e1-ft#https://github.com/notifications/beacon/ADqqzn6QQZ0GpSyFgnseLZtWnggtvlcwks5pkMrHgaJpZM4HZ7oN.gif
>

-- 
Sent from my iPhone
