### ISSUE TITLE
change background color? 

### ISSUE THREAD

**Issue by suberlak** [dunovank/jupyter-themes#150]
Hi!
I'm sorry but I couldn't find anywhere a way to customize background color.  Specifically,  I like 
`jt -t onedork -f roboto -fs 12  -ofs 10 `
but when I plot a figure the axes are labeled with font in black, which is very hard to see on the output background.  Can I modify the output background in that theme ? 

Best wishes
Chris 

(attached example figure)
<img width="618" alt="screen shot 2017-07-12 at 8 03 53 pm" src="https://user-images.githubusercontent.com/5504371/28148708-4ea9e1fc-673d-11e7-991f-d09207cf5ba4.png">

**Comment by dunovank** [comment]
when you start a notebook, run:
```py
# import jtplot
from jupyterthemes import jtplot

# you can select an alternative theme's plot style by name
# onedork | grade3 | oceans16 | chesterish | monokai | solarizedl | solarizedd
jtplot.style('onedork')
```

may have to update jupyterthemes to use jtplot (depending on what version you currently have installed) 
```
# install/upgrade to latest version
pip install --upgrade jupyterthemes
```

**see README info about [jtplot ](https://github.com/dunovank/jupyter-themes#set-plotting-style-from-within-notebook)**

**Comment by jjongjjong** [comment]
div.output_wrapper {
 background-color: #ffffff;  <- change this to #ffffff in jupyter css file
 border: 0px;
 left: 0px;
 margin-bottom: 0em;
 margin-top: 0em;
 border-top-right-radius: 0px;
 border-top-left-radius: 0px;
}

**Comment by zhenghongyu** [comment]
> div.output_wrapper {
> background-color: #ffffff; <- change this to #ffffff in jupyter css file
> border: 0px;
> left: 0px;
> margin-bottom: 0em;
> margin-top: 0em;
> border-top-right-radius: 0px;
> border-top-left-radius: 0px;
> }

Perfect!
