### ISSUE TITLE
No module named 'jupyter_core'

### ISSUE THREAD

**Issue by OldBoots4** [dunovank/jupyter-themes#153]
I get the error below when:
    giving terminal command: jt -t oceans16
          ModuleNotFoundError: No module named 'jupyter_core'

When giving terminal command: conda -l
         jupyter_core  4.3.0  py36_0   is listed in the modules

Any ideas as to cause, or solution to problem?

**Comment by edencakir** [comment]
+ 1

**Comment by dunovank** [comment]
Thanks for the feedback, working on a fix now

**Comment by dunovank** [comment]
@OldBoots4 can you try running `pip install --upgrade jupyterthemes` to see if the issue is fixed?

**Comment by OldBoots4** [comment]
Thanks for the help dunovank, 
 I did the pip  upgrade jupyterthemes and then received  the ModuleNotFoundError: No module named 'lesscpy' error.  
After pip install lesscpy was applied, the jupyter-theme has been applied to my notebook and looks great!
Thank you again for the help and also the rapid response.

**Comment by dunovank** [comment]
I'm pretty sure the root of this error is the same as #149 , hoping both have been resolved in the newest release. Anyone mind testing it out? `pip install --upgrade jupyterthemes`

**Comment by dunovank** [comment]
Reported as fixed in #149 . Closing.

**Comment by hljames** [comment]
I had the same problem and can confirm that `pip install --upgrade jupyterthemes` fixed it!

**Comment by TareqMonwer** [comment]
It worked for me too. I just have to give` _sudo pip3 install --upgrade notebook_`

**Comment by togarci** [comment]
Tks

**Comment by moazbk** [comment]
Thank you Man it worked

**Comment by alexisdurieux** [comment]
Also for those who have this issue you might want make some cleaning in your ~/.local/bin directory and performign and installation again

**Comment by jm-ss** [comment]
hope it will be work...

**Comment by weijian001** [comment]
Thank you. It works for me.@edencakir

**Comment by janvaljan7** [comment]
> @OldBoots4 can you try running `pip install --upgrade jupyterthemes` to see if the issue is fixed?

Thank you so much. The problem is gone :)

**Comment by raymond0208** [comment]
The two commands worked for me

**Comment by Lebhoryi** [comment]
thx, it help me a lot.

**Comment by jitendrakumarkushwaha** [comment]
Got similar issue & Fixed after removing the user from the sudo group in ubuntu.

sudo deluser jitendra sudo

**Comment by Lawrence-Krukrubo** [comment]
> I had the same problem and can confirm that `pip install --upgrade jupyterthemes` fixed it!

Thanks a lot as the above line sure fixed it for me too!

**Comment by glorytheksy** [comment]
> +1
> 
> **Edit**:
> @OldBoots4
> I did this: `pip3 install --upgrade notebook`
> and this: `pip3 install lesscpy` and it worked. Enjoying onedork.
> 
> (you may need to replace pip3 with pip)

Thanks a lot!

**Comment by zivlang** [comment]
I tried the above solutions, yet the problem reappears.

**Comment by flashjames** [comment]
This post (using conda-forge, as https://jupyter.org/install recommends withot showing how)

https://towardsdatascience.com/how-to-set-up-anaconda-and-jupyter-notebook-the-right-way-de3b7623ea4a

Basically it's:
conda install -c conda-forge notebook
conda install -c conda-forge nb_conda_kernels
