### ISSUE TITLE
The code cell numbers a

### ISSUE THREAD

**Issue by ozkansafak** [dunovank/jupyter-themes#154]
Hello,

I installed the themes and was going through them. Then, I realized the cell numbers have disappeared for all the themes I have tried, light and dark themes alike.  Can't use it without being able to see which cells the Python kernel has run etc.
I had to `jt -r` it. 
Is this common?
Thanks

![image](https://user-images.githubusercontent.com/1207494/28401776-27b0b046-6cd1-11e7-9c58-0136b4bae7d1.png)

**Comment by dunovank** [comment]
what arguments did you provide when installing the theme? This is intended to happen when the user provides `-altp` (or `--altprompt`)  as an argument. Makes the prompt thinner, removes the cell number. But I want to make sure this isn't happening by default.

**Comment by ozkansafak** [comment]
Ah the `-altp`!!

I was using this: `jt -t grade3 -fs 95 -altp -tfs 11 -nfs 115 -cellw 66% -nf opensans` without knowing that the `-altp` bit removed the cell numbers. 

I took that argument out now.  The cell numbers are back and I'm happy.

Thanks and Rock on!

**Comment by dunovank** [comment]
Cool. Closing this then.
