### ISSUE TITLE
PermissionError: [WinError 32] 

### ISSUE THREAD

**Issue by Strong-Curious** [dunovank/jupyter-themes#155]
Hi!

After installation (Windows 10 with Anaconda), i'm trying to execute:

`jt -t chesterish `

and getting:

`Traceback (most recent call last):
  File "c:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\Scripts\jt.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\lib\site-packages\jupyterthemes\__init__.py", line 285, in main
    dfonts=args.defaultfonts)
  File "c:\anaconda3\lib\site-packages\jupyterthemes\__init__.py", line 103, in install_theme
    stylefx.remove_temp_file()
  File "c:\anaconda3\lib\site-packages\jupyterthemes\stylefx.py", line 77, in remove_temp_file
    os.remove(tempfile)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RON-)~1\\AppData\\Local\\Temp\\tmplld5nh_h.less'`

What is wrong ?

Thanks!

**Comment by dunovank** [comment]
What version of jupyter-themes are you running? You can figure this out by running the following code in a notebook:

```py
import jupyterthemes as jt
jt.__version__
```

**Comment by dbeley** [comment]
Same problem here, on windows 7 x64 with the Anaconda environment.

`PermissionError: [WinError 32] Le processus ne peut pas accéder au fichier car c
e fichier est utilisé par un autre processus: 'C:\\Users\\login\\AppData\\Loca
l\\Temp\\tmp2qqhmk34.less'`

jupyter-themes version 0.17.0

**Comment by dunovank** [comment]
Hi thanks for the feedback y'all and sorry for the bug. Hoping this issue has been fixed in version 0.17.3. Would someone mind updating to the newest release and posting back here if the issue has been resolved or not? 

`pip install --upgrade jupyterthemes`

**Comment by dunovank** [comment]
@dbeley @Strong-Curious @jojonki ?

**Comment by Strong-Curious** [comment]
Working !!!!
Thank you very much !!!

**Comment by dunovank** [comment]
Good to hear, thanks. Closing
