### ISSUE TITLE
Set axis color

### ISSUE THREAD

**Issue by iamtodor** [dunovank/jupyter-themes#159]
Is it possible to change axis color? I use `chesterish syntax` theme and it's hard to see axis labels.
<img width="779" alt="screen shot 2017-07-25 at 09 14 57" src="https://user-images.githubusercontent.com/12586108/28558262-ced51e4c-7119-11e7-9c41-f5e13f8f199b.png">

**Comment by dunovank** [comment]
See README on [jtplot.style()](https://github.com/dunovank/jupyter-themes#set-plotting-style-from-within-notebook)
