### ISSUE TITLE
An Option to set font size of Mathematical Symbols

### ISSUE THREAD

**Issue by bhanubais** [dunovank/jupyter-themes#163]
Currently all Font size of mathematical objects are quite small. I can increase it's size by using `-tfs <font-size>` but it also increases normal text's size.
I think this There is feature which is missing but very easy to integrate A flag for only "Font size of Mathematical Symbols" e.g.  

`jt -t grade3 -fm 15`

If we hit this command font size of mathematical object should be changed to 15px.

**Comment by dunovank** [comment]
I'll add this in the next release, thanks for the input! Will use the flag `-mathfs` (mathfontsize)

**Comment by bhanubais** [comment]
Hi dunovank,
Thanks for implementing mathfontsize flag. But It is not still working. It only increasing the line height of mathematical fonts instead of font-size.

**Comment by dunovank** [comment]
ahh sorry about that, I'll reopen the issue then and post an update when fixed. thanks!

**Comment by dunovank** [comment]
closing this (duplicate of #175 )
