### ISSUE TITLE
jt -r should not reset .jupyter/custom

### ISSUE THREAD

**Issue by jarmitage** [dunovank/jupyter-themes#167]
When I use `jt -r` I want to go back to the default theme, but I do not want to delete my custom css in `.jupyter/custom`.

For example I have `.container { width: 95% !important; }` in `custom.css` which I want to keep

**Comment by dunovank** [comment]
Sorry but since jupyterthemes writes directly over any custom.css file I'm inclined to keep the current functionality for removing the custom.css file. That said, make sure you generate a copy of any custom.css you've written so you can copy it back to .jupyter/custom whenever you want to reset.
