### ISSUE TITLE
pdf format

### ISSUE THREAD

**Issue by mrajancsr** [dunovank/jupyter-themes#168]
Hello this might  not really be an issue, but I am having trouble converting your ipython dark themes to pdf format.  I have a mac os.  For some reason, all the pdfs come in white, but the plots come in the right color.  Is there any way I can match the pdf to the actual theme color?  Thanks

**Comment by dunovank** [comment]
Yeah this is more challenging than I thought. Tried to do this several times but it was admittedly quite a long time ago so maybe things have gotten easier recently. Feel free to submit a PR if you figure something out. Thanks!
