### ISSUE TITLE
can't uninstall

### ISSUE THREAD

**Issue by sanjuprk** [dunovank/jupyter-themes#172]
both the following commands for uninstalling using pip doesn't seem to work, any help?
> pip uninstall jupyterthemes
> pip uninstall jupyter-themes

**Comment by dunovank** [comment]
Whats the output of the uninstall commands? Does it give an error? Can you try re-installing the latest version?
```
 pip install --upgrade jupyterthemes
```

I wasn't able to reproduce this error so will need some more information about which version of JT you have installed, your system, conda env, etc.

Sorry for the trouble.

**Comment by sanjuprk** [comment]
Tried re-installing , Worked! 
Thanks..!
