### ISSUE TITLE
Can't apply jupyter-themes to pycharm

### ISSUE THREAD

**Issue by HuangYanfei** [dunovank/jupyter-themes#176]
after I setting the theme for jupyter notebook on browser, it works. But the notebook in pycharm still remain  the same.

**Comment by J216** [comment]
Just use punch cards, everything has gone way too far.

Best Regards,


Jared Haer
Owner/Operator
Haer Design & Development
918 N 24th ST, St. Joseph, MO 64506
Phone: (660) 541-1026

**Comment by dunovank** [comment]
@HuangYanfei not sure how easy pycharm integration would be. feel free to submit a PR though if you figure something out.

@J216 what are you referring to?
