### ISSUE TITLE
Terminal can not show the full line

### ISSUE THREAD

**Issue by xwjabc** [dunovank/jupyter-themes#189]
It seems there is some problem about the display in terminal. Consider using the setting in the doc:

jt -t onedork -fs 95 -altp -tfs 11 -nfs 115 -cellw 88% -T

In a terminal session created on Jupyter, the output will be only half size:

<img width="360" alt="screen shot 2017-10-13 at 11 45 35 am" src="https://user-images.githubusercontent.com/16413829/31561249-1d31a6ce-b00c-11e7-8ee4-f96ec67cebfb.png">

If I zoom out and then zoom in the webpage, the output can restore to normal full size:

<img width="382" alt="screen shot 2017-10-13 at 11 45 39 am" src="https://user-images.githubusercontent.com/16413829/31561287-3bbc8eb0-b00c-11e7-980f-04c3b9671894.png">

However, if I refresh the page, the half size problem occurs again.

**Comment by neos2008** [comment]
Maybe you can try this: jt -t onedork -fs 95 -altp -tfs 11 -nfs 115  -T. It works out for me by removing the -"cellw 88%" .

**Comment by konmeo** [comment]
Confirm "-cellw %" is the culprit.

jupyter/notebook#46 provides some insight into this problem.

@xwjabc, thanks for the work-around tip to restore normal size.
