### ISSUE TITLE
Doesn't effect table of contents plugin

### ISSUE THREAD

**Issue by gnsiva** [dunovank/jupyter-themes#193]
I use this awesome jupyter plugin:
http://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/toc2/README.html

The floating and side anchored table of contents is not coloured according to the theme. The font is larger and less attractive than usual as well. 

It would be great if jupyterthemes would change the colour of it as well and have smaller fonts there.

![image](https://user-images.githubusercontent.com/4519814/32059282-8fa175a2-ba63-11e7-86c4-067f1198f8b0.png)

**Comment by zhiyzuo** [comment]
+1

**Comment by liuzhiwei** [comment]
+1

**Comment by dunovank** [comment]
I added styling for this extension in the latest release. would someone mind testing it for me? (no flags are required, just upgrade and re-install your theme. also be sure to refresh your browser cache after upgrading/updating theme).

**Comment by gnsiva** [comment]
Thanks! Just tested it, the colours look great now! 🙂 
One point is it would be nice if the font size was smaller for it, it is a lot bigger than the original.

**Comment by dunovank** [comment]
will make it a bit smaller in future versions. thanks

**Comment by lukelbd** [comment]
@dunovank Just wanted to say you are *awesome* for addressing this. Thanks so much!

**Comment by dunovank** [comment]
no problem, glad it worked!
