### ISSUE TITLE
How to change code font in the theme?

### ISSUE THREAD

**Issue by argman** [dunovank/jupyter-themes#20]
I tried to change the .CodeMirror part of custom.css, but seems the font in the web does not change.
.CodeMirror pre {
  font-family: 'Monaco';
  font-size: 13pt;
}

**Comment by dunovank** [comment]
I added a cl option (-f) to set font and changed the argument for setting font-size to -fs (see the updated README instructions for example). See if that works.

**Comment by dunovank** [comment]
closing this

**Comment by ezmiller** [comment]
How would you set the font from within a notebook?
