### ISSUE TITLE
Header and toolbar missing even after uninstalling

### ISSUE THREAD

**Issue by diedummydie** [dunovank/jupyter-themes#201]
After installing, the Jupyter header and toolbar are missing. Selecting View > Toggle Header or View > Toggle Toolbar has no effect. (Toggle Line Numbers and Cell Toolbar options are unaffected.)

I want the Jupyter header and toolbar. 

`pip uninstall jupyterthemes` did not bring these features back.

**Comment by diedummydie** [comment]
`conda update --all --force` also did not resolve the issue.

**Comment by diedummydie** [comment]
`rm -rf ~/.jupyter/custom` did not resolve the issue.

**Comment by diedummydie** [comment]
`pip install --upgrade --force-reinstall jupyter` worked. It did restore jupyter to its state prior to having its layout altered by this project. 

I thought this project only offered syntax themes. I didn't realize it comes with a new UI theme that permanently makes it impossible to access built-in functionality while also centering H1 headers in Markdown, ignoring trailing line-breaks, and other undesired alterations.

**Comment by dunovank** [comment]
deep breaths buddy. 

for anyone who runs into this issue in the future, you can try the following fixes:

1. if you've uninstalled jupyterthemes and cannot see the toolbar, try clicking the 'View' dropdown menu in a notebook and then 'Toggle Toolbar'. 

2. If that doesn't work, then try reinstalling jupyterthemes, then  reset to the default UI 
```jt -r``` (if still not fixed, try step 1 again after running the reset command)

3. If you're still toolbar-less, then try installing a theme with the toolbar toggled on `jt -t grade 3 -T` (then steps 2 and 1)

**Comment by EnJiang** [comment]
@dunovank 's solution worked for me perfectly.
`jt -t chesterish` leads to toolbar-less (toggle toolbar also not respond), `jt -t chesterish -T` and problem solved.

**Comment by hugogiacomini** [comment]
> @dunovank 's solution worked for me perfectly.
> `jt -t chesterish` leads to toolbar-less (toggle toolbar also not respond), `jt -t chesterish -T` and problem solved.

This worked for me as well

**Comment by kirkanshin** [comment]
`-T`works for the toolbar, is there a way to bring back the header too?

**Comment by N0D0** [comment]
> `-T`works for the toolbar, is there a way to bring back the header too?

-N
