### ISSUE TITLE
jupyter cell output mis alignment

### ISSUE THREAD

**Issue by bicepjai** [dunovank/jupyter-themes#203]
The jupyter code cell output gets mis aligned when the themes are applied. how can we make this fully visible. I have attached an image for reference. [jupyter-ouput-misalignment](https://imagebin.ca/v/3hDHdXq6FHOM)

**Comment by bicepjai** [comment]
any updates ?

**Comment by dunovank** [comment]
hmm I've not had this issue. What CL arguments/values are you using when you install your theme?

**Comment by coldplug** [comment]
Hello, the same problem here. As far as I can see, any theme, any cellw... for example
jt -t monokai -cellw 80% -T

**Comment by u1z** [comment]
I assume it's a padding or alignment issue with the css. Does anyone know the location for the prompt output or the hover bar when hovering over a prompt output? This seems to overlap with the output.

**Comment by FraserHum** [comment]
I'm having the same issue, any idea how to solve it? Seems to happen no matter what arguments I use

**Comment by skokado** [comment]
I'm having the same issue. I'm using version 0.19.6 by anaconda.
I applied a below commands,
`jt -t monokai -f generic -T -N`
![default](https://user-images.githubusercontent.com/16687062/44456400-5b4f3900-a63b-11e8-8a48-9d9a709ad89f.PNG)

![default](https://user-images.githubusercontent.com/16687062/44456577-dd3f6200-a63b-11e8-80c1-3b96270b27e6.png)

![2](https://user-images.githubusercontent.com/16687062/44456582-df092580-a63b-11e8-809e-ddecb9b8e2b7.png)


I think, the width of output cell should be the same with width of input cell.

**Comment by vaughnkoch** [comment]
I've noticed this as well. I traced it to a commit between 0.19.4 and 0.19.5: 
https://github.com/dunovank/jupyter-themes/compare/v0.19.4...v0.19.5

I'm using `jt -t monokai -cellw 100% -T`.
I did `jt -r` to reset between theme changes.

**Comment by FraserHum** [comment]
I have solved the issue by removing the out_prompt_overlay from the css file and actually found there was another normally functioning prompt underneath it. I can post more info when I get home if anyone needs it

**Comment by danny-moncada** [comment]
@FraserHum would you mind posting what you had to change in the CSS file to get the output to align properly?  I've been trying myself and having no luck... any help would be greatly appreciated!

**Comment by goelo** [comment]
Hi guys, any solution?I'm stuck in that...

**Comment by Chmavo** [comment]
@FraserHum more info on the modifications you made to the CSS files to fix this issue would be appreciated!

**Comment by FraserHum** [comment]
[custom.zip](https://github.com/dunovank/jupyter-themes/files/2365039/custom.zip)

I deleted the parts that were causing problems instead of putting it to display: none which makes remembering what I changed difficult but hopefully you can find the differences between my custom.css and yours. It should be called output_prompt or something like that.

**Comment by Chmavo** [comment]
@FraserHum thank you very much for the reply. This worked for me. I added display:none to out_prompt_overlay and now I can see the full output.

**Comment by Space-G** [comment]
In the custom.css file, I fixed it by changing both the **div.out_prompt_overlay.prompt**'s and the **div.out_prompt_overlay.prompt:hover**'s min-width and width values to 11.5ex instead of the original 14.5ex.
This makes the button that is covering the output smaller, instead of completely removing it
![jupyter](https://user-images.githubusercontent.com/39596472/46251192-9c98ec80-c422-11e8-865c-6e98d7625c99.png)

**Comment by chopan123** [comment]
> In the custom.css file, I fixed it by changing both the **div.out_prompt_overlay.prompt**'s and the **div.out_prompt_overlay.prompt:hover**'s min-width and width values to 11.5ex instead of the original 14.5ex.
> This makes the button that is covering the output smaller, instead of completely removing it
> ![jupyter](https://user-images.githubusercontent.com/39596472/46251192-9c98ec80-c422-11e8-865c-6e98d7625c99.png)

by custom.css file do you mean <theme>.css? for example onedork.css? It does not work for me :(

**Comment by Space-G** [comment]
> > In the custom.css file, I fixed it by changing both the **div.out_prompt_overlay.prompt**'s and the **div.out_prompt_overlay.prompt:hover**'s min-width and width values to 11.5ex instead of the original 14.5ex.
> > This makes the button that is covering the output smaller, instead of completely removing it
> > ![jupyter](https://user-images.githubusercontent.com/39596472/46251192-9c98ec80-c422-11e8-865c-6e98d7625c99.png)
> 
> by custom.css file do you mean .css? for example onedork.css? It does not work for me :(

The file is called `custom.css`, and I'm using windows so it's located in `C:\Users\<YourUsername>\.jupyter\custom\custom.css`

**Comment by Idodox** [comment]
I've got the same issue, output is clipped.
I'm on a mac, and jupyter\custom\custom.css is nowhere to be found.
anyone know where to find it?

I tried also changing cells.less but it had no effect.

**Comment by yangrq1018** [comment]
@FraserHum That works! Thanks a lot.

**Comment by hey-simone** [comment]
@Idodox I'm also on a mac. Make the hidden files visible and you can find the .jupyter folder with the custom.css at the same path.
