### ISSUE TITLE
lesscpy>=0.12.0

### ISSUE THREAD

**Issue by japhar81** [dunovank/jupyter-themes#213]
Looks like there's no lesscpy 0.12? I'm not sure if it was pulled or something, I see some references in google, but it doesn't appear to exist. Getting this error on install;
```
Collecting lesscpy>=0.12.0 (from jupyterthemes)
  Could not find a version that satisfies the requirement lesscpy>=0.12.0 (from jupyterthemes) (from versions: 0.9d, 0.9e, 0.9f, 0.9g, 0.9h, 0.9i, 0.9i.linux-x86_64, 0.9j, 0.6, 0.9a0, 0.9rc0, 0.10, 0.10.1, 0.10.2, 0.11.1, 0.11.2)
No matching distribution found for lesscpy>=0.12.0 (from jupyterthemes)
```

**Comment by sidpathak92** [comment]
Same here. Even after installing lesscpy, the same error above persists.

**Comment by ckaros** [comment]
confirmed. lesscpy 0.12 is not on PyPi

**Comment by ckaros** [comment]
I was able to find a copy of the lesscpy 0.12.0 whl on the (PyPi page cached by google). [https://webcache.googleusercontent.com/search?q=cache:D2spM_D8dN8J:https://pypi.python.org/pypi/lesscpy+&cd=1&hl=en&ct=clnk&gl=us&client=firefox-b-1#downloads]

**Comment by rohanlolm** [comment]
The current version of lesscpy appears to be 0.11.2 failing the >=0.12.0 dependency

**Comment by PegasusWithoutWings** [comment]
I am having the exact same problem. It is stopping me from installing this package in my new machine.

**Comment by amer** [comment]
A fast fix 
```bash
wget https://pypi.python.org/packages/32/38/a55150ec018cf6fe11012bf1d988cd737af7f82227e4ac753619f0fb27a4/lesscpy-0.12.0.tar.gz
pip install lesscpy-0.12.0.tar.gz
pip install jupyterthemes
```

**Comment by aldanor** [comment]
Or just...

```
pip install https://pypi.python.org/packages/32/38/a55150ec018cf6fe11012bf1d988cd737af7f82227e4ac753619f0fb27a4/lesscpy-0.12.0.tar.gz
pip install jupyterthemes
```

**Comment by hmgl** [comment]
https://github.com/conda-forge/lesscpy-feedstock. Install under Python2.7.

**Comment by dunovank** [comment]
Hi everyone, I'm very sorry for the delay in addressing this issue (I've been away on vacation and neglecting my support duties :/

(Also a HUGE thanks to everyone who has helped out in my absence responding to user issue reports!)

I see that the PR submitted by @PegasusWithoutWings raises errors on TravisCL. Sometimes this occurs without impacting the actual functionality of JT but I just want to make sure that the PR solves the issue on both Python 2 and 3. Can anyone confirm this?

**Comment by dunovank** [comment]
I've pushed an update that fixes the install issue and can confirm install/upgrade works with Python 3 distributions. Please report any problems back here and I'lll do my best to address them in a timely manner. Thanks again y'all!

**Comment by dunovank** [comment]
has anyone had a chance to install/upgrade to the latest release (v0.18.3)?

**Comment by japhar81** [comment]
@dunovank not yet, but I intend to give it a try tonight

**Comment by dunovank** [comment]
great thanks @japhar81

**Comment by dunovank** [comment]
@japhar81 any chance you've checked this yet?

**Comment by japhar81** [comment]
@dunovank apologies -- I did and confirmed it's working. Apparently I forgot to comment on here.

**Comment by dunovank** [comment]
@japhar81 no worries, thanks for checking!
