### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by mlx809593812** [dunovank/jupyter-themes#218]
how can I solve decode problem like this.

UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 41271: illegal multibyte sequence

**Comment by aiqu** [comment]
Try this(https://github.com/dunovank/jupyter-themes/pull/216). I had the same problem

**Comment by mlx809593812** [comment]
Thank you.But I still not solve this problem in windows...

**Comment by aiqu** [comment]
Could you explain more details?

I tried as below, and I think it could solve your problem.

- I converted original notebook.less file to ASCII format using iconv tool and named it as 'notebook.less.ascii'
- Without encoding parameter, it reads well
- However, with 'gbk' encoding, it fails as you experienced
- Finally, use converted file with 'gbk' encoding works well!

![image](https://user-images.githubusercontent.com/6983111/34637788-ce5b9c84-f300-11e7-98e6-369c484a9c1f.png)

**Comment by mlx809593812** [comment]
@aiqu Thank you for your help!
This is my problem:UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 41271: illegal multibyte sequence
The system I used is windows,I can not use the iconv tool to converted file with 'gbk' encoding

**Comment by aiqu** [comment]
This is converted file, save it as 'notebook.less'
[notebook.less.txt](https://github.com/dunovank/jupyter-themes/files/1608587/notebook.less.txt)

and replace your notebook.less file in your site-packages/jupytherthemes/layout

It will work :D

**Comment by mlx809593812** [comment]
@aiqu 
Wow, it really works!
Thank you very much！

**Comment by dunovank** [comment]
Would someone mind upgrading to version 0.18.8 to see if this is fixed? And could you report your results back here? Thanks!  

```sh
pip install --upgrade jupyterthemes
```

**Comment by dunovank** [comment]
Has been fixed in v0.18.9 (see duplicate issues #217 and #220 )
