### ISSUE TITLE
Change the theme when there is a problem, I found a long time to solve, no effect finally can't, can only come to you for help, I hope you can help me!

### ISSUE THREAD

**Issue by ZhangHongdaZWQ** [dunovank/jupyter-themes#222]
After the previous python themes installation, I tried to use the topic.

Input: JT - t ocean s16.

An error then occurred stating: "' gbk' codec can' t decode byte 0x8b in position 41271: illegall multibyte sequence".

I don't know what this means, so I hope you can help me solve this problem, thank you!

**Comment by dunovank** [comment]
Hi @ZhangHongdaZWQ, 

Is that the exact text you entered? There shouldn't be any space between 'ocean' and 's16', and `jt` should be lowercase. So It should be:

```
jt -t oceans16
```

What's your Python version, jupyterthemes version, and operating system?

if you run the following line:
```
pip install --no-dependencies jupyterthemes==0.18.2
```

then run:
```
jt -t oceans16
```

Does this fix the issue?

**Comment by ZhangHongdaZWQ** [comment]
First, thank you for answering my question. I have solved my problem, I entered exactly this, uppercase may have changed the format, the computer default uppercase. But now I have a question to ask you, I have installed this theme, why when I opened it is not like the page shows the interface, but changed the color only, the preview page on the theme of how those Get it? I hope you can help me, thank you!

**Comment by ZhangHongdaZWQ** [comment]
First, thank you for answering my question. I have solved my problem, I entered exactly this, uppercase may have changed the format, the computer default uppercase. But now I have a question to ask you, I have installed this theme, why when I opened it is not like the page shows the interface, but changed the color only, the preview page on the theme of how those Get it? I hope you can help me, thank you!@dunovank
