### ISSUE TITLE
Can't open startup.ipy

### ISSUE THREAD

**Issue by HwijaeSon** [dunovank/jupyter-themes#223]
Hi guys. 

I'm trying to open the ~/.ipython/profile_default/startup/startup.ipy file to use the plotting theme. 

I did  $ ipython profile create 

so the directory ~/.ipython/profile_default/startup is already created.

But the problem is, there is no startup.py file in the directory. 

How can I fix this?

**Comment by dunovank** [comment]
create a file named `startup.ipy` and save it to your startup directory that ipython created.
