### ISSUE TITLE
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 ....

### ISSUE THREAD

**Issue by rightx2** [dunovank/jupyter-themes#226]
I'm Korean and use Window7 as an OS.

I successfully installed jupyterthemes and tried to apply,

`jt -T -t grade3`

But it occurs errors:
```
File "c:\users\chois\miniconda3\envs\my_virtual_env\lib\site-packages\jupyterthemes\stylefx.py", link 291, in style_layout
    style_less += notebook.read() + '\n'
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 41269: illegal multibyte sequence
```

How can I solve this issues?

**Comment by dunovank** [comment]
I just released a new version with a PR intended to fix the encoding error. Can you try upgrading to the latest version and let me know if this issue is resolved? Thanks!

**Comment by rightx2** [comment]
@dunovank  Work well :) Thanks for accepting pull request 👍

**Comment by Takanashikoucha** [comment]
C:\Users\koucha
λ  pip install --upgrade jupyterthemes
Requirement already up-to-date: jupyterthemes in c:\python35\lib\site-packages
Requirement already up-to-date: ipython>=5.4.1 in c:\python35\lib\site-packages (from jupyterthemes)
Requirement already up-to-date: lesscpy>=0.11.2 in c:\python35\lib\site-packages (from jupyterthemes)
Requirement already up-to-date: matplotlib>=1.4.3 in c:\python35\lib\site-packages (from jupyterthemes)
Requirement already up-to-date: jupyter-core in c:\python35\lib\site-packages (from jupyterthemes)
Requirement already up-to-date: setuptools>=18.5 in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: decorator in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: pickleshare in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: colorama; sys_platform == "win32" in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: pygments in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: simplegeneric>0.8 in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.4 in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes) Requirement already up-to-date: jedi>=0.10 in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: win-unicode-console>=0.5; sys_platform == "win32" and python_version < "3.6" in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: traitlets>=4.2 in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: six in c:\python35\lib\site-packages (from lesscpy>=0.11.2->jupyterthemes)
Requirement already up-to-date: ply in c:\python35\lib\site-packages (from lesscpy>=0.11.2->jupyterthemes)
Requirement already up-to-date: pytz in c:\python35\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already up-to-date: numpy>=1.7.1 in c:\python35\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already up-to-date: cycler>=0.10 in c:\python35\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already up-to-date: python-dateutil>=2.1 in c:\python35\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already up-to-date: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\python35\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already up-to-date: wcwidth in c:\python35\lib\site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: parso==0.1.1 in c:\python35\lib\site-packages (from jedi>=0.10->ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: ipython-genutils in c:\python35\lib\site-packages (from traitlets>=4.2->ipython>=5.4.1->jupyterthemes)
C:\Users\koucha
λ  jt -t onedork -fs 95 -altp -tfs 11 -nfs 115 -cellw 80% -T -N
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python35\Scripts\jt.exe\__main__.py", line 9, in <module>
  File "c:\python35\lib\site-packages\jupyterthemes\__init__.py", line 305, in main
    dfonts=args.defaultfonts)
  File "c:\python35\lib\site-packages\jupyterthemes\__init__.py", line 98, in install_theme
    nbname=nbname)
  File "c:\python35\lib\site-packages\jupyterthemes\stylefx.py", line 291, in style_layout
    style_less += notebook.read() + '\n'
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8b in position 41271: illegal multibyte sequence
C:\Users\koucha
λ
-------------------------------------------
upgraded but still error

**Comment by bonzyfonzy** [comment]
Same issue here. lol

UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 41269: illegal multibyte sequence

**Comment by dunovank** [comment]
Would someone mind upgrading to version 0.18.8 to see if this is fixed? And could you report your results back here? Thanks!  

```sh
pip install --upgrade jupyterthemes
```

**Comment by Takanashikoucha** [comment]
#This has been fixed
----------log-----------

# koucha at KOUCHA_PC in ~ [2:49:44]
⚡ ➜ pip install --upgrade jupyterthemes
Requirement already up-to-date: jupyterthemes in c:\python35\lib\site-packages
Requirement already up-to-date: lesscpy>=0.11.2 in c:\python35\lib\site-packages (from jupyterthemes)
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out. (read timeout=15)",)': /simple/ipython/
Requirement already up-to-date: ipython>=5.4.1 in c:\python35\lib\site-packages (from jupyterthemes)
Requirement already up-to-date: jupyter-core in c:\python35\lib\site-packages (from jupyterthemes)
Requirement already up-to-date: matplotlib>=1.4.3 in c:\python35\lib\site-packages (from jupyterthemes)
Requirement already up-to-date: six in c:\python35\lib\site-packages (from lesscpy>=0.11.2->jupyterthemes)
Requirement already up-to-date: ply in c:\python35\lib\site-packages (from lesscpy>=0.11.2->jupyterthemes)
Requirement already up-to-date: decorator in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: win-unicode-console>=0.5; sys_platform == "win32" and python_version < "3.6" in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: pygments in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: simplegeneric>0.8 in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: setuptools>=18.5 in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: colorama; sys_platform == "win32" in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.4 in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: jedi>=0.10 in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: pickleshare in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: traitlets>=4.2 in c:\python35\lib\site-packages (from ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: pytz in c:\python35\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already up-to-date: python-dateutil>=2.1 in c:\python35\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)

Requirement already up-to-date: cycler>=0.10 in c:\python35\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already up-to-date: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\python35\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already up-to-date: numpy>=1.7.1 in c:\python35\lib\site-packages (from matplotlib>=1.4.3->jupyterthemes)
Requirement already up-to-date: wcwidth in c:\python35\lib\site-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: parso==0.1.1 in c:\python35\lib\site-packages (from jedi>=0.10->ipython>=5.4.1->jupyterthemes)
Requirement already up-to-date: ipython-genutils in c:\python35\lib\site-packages (from traitlets>=4.2->ipython>=5.4.1->jupyterthemes)
# koucha at KOUCHA_PC in ~ [2:50:13]
⚡ ➜ jt -t onedork -fs 95 -altp -tfs 11 -nfs 115 -cellw 88% -T -N
# koucha at KOUCHA_PC in ~ [2:50:41]
⚡ ➜

**Comment by dunovank** [comment]
Great, thanks!
