### ISSUE TITLE
jt -t grade3  error in python2.7  

### ISSUE THREAD

**Issue by gotope** [dunovank/jupyter-themes#228]
$  jt -t grade3 -T
Traceback (most recent call last):
  File "/usr/local/bin/jt", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyterthemes/__init__.py", line 305, in main
    dfonts=args.defaultfonts)
  File "/usr/local/lib/python2.7/dist-packages/jupyterthemes/__init__.py", line 98, in install_theme
    nbname=nbname)
  File "/usr/local/lib/python2.7/dist-packages/jupyterthemes/stylefx.py", line 290, in style_layout
    with open(nb_style, 'r', encoding='utf8', errors='ignore') as notebook:
TypeError: file() takes at most 3 arguments (4 given)

**Comment by jstitlow** [comment]
Also getting this error.

**Comment by davegreenwood** [comment]
The arguments for open are different for python 2 and 3, a possible work around is to remove the extra arguments (find and replace , encoding='utf8' and , errors='ignore' wit nothing ) not forgetting the commas... and change the mode to binary 'r' ->'rb' and 'w'->'wb'.

this works, but is not thoroughly tested, so caution is advised.

**Comment by davegreenwood** [comment]
update:
applying the changes from my previous comment, I tried the command:

`$ jt -t onedork -fs 11 -altp -tfs 11 -nfs 11 -ofs 11 -cellw 88% -T`

and the style seems properly applied, although this is the first time I've used this package!

**Comment by jstitlow** [comment]
Thanks @davegreenwood!

Would it be to much to ask for you to share the specific modification you made to remove the extra arguments and how exactly you changed the parse mode to binary?
j

**Comment by davegreenwood** [comment]
hi, sorry I missed the important detail of editing the file reported in the error:

`<YOUR INSTALLATION>/python2.7/dist-packages/jupyterthemes/stylefx.py`

and, for example find:

`with open(nb_style, 'r', encoding='utf8', errors='ignore') as notebook:`

and change to:

`with open(nb_style, 'rb') as notebook:`

and all other examples of calling open()...

NB. you also need to change write mode too ,  'w' becomes 'wb' for all lines you can find.

sorry, I didn't record my line numbers.

**Comment by jstitlow** [comment]
Works for me. 
Great stuff @davegreenwood!
j

**Comment by gotope** [comment]
yep, it works.
thanks

**Comment by wiharto** [comment]
it works! thanks @davegreenwood!

**Comment by RickyMcMaster** [comment]
Works!  Thanks @davegreenwood
