### ISSUE TITLE
Subheading format markdown

### ISSUE THREAD

**Issue by dektoud** [dunovank/jupyter-themes#229]
First, thanks for this package. I love the freshened look of my notebooks. 

I am wondering how I can make subheadings in markdown cells have a similar format (e.g. centered, blue) as the first heading (`# heading1`).
e.g.:
![jt_header](https://user-images.githubusercontent.com/14908618/36117801-34348f0c-0ff8-11e8-93aa-8ec3f3832b2b.gif)
Is it possible to unify the styling of the subheadings to match that first one? i'm not really sure where to look. 

Thanks!
Ryan

**Comment by dektoud** [comment]
I ended up figuring out the area in `custom.css` that I had to modify, then tracked that down to the `cells.less`. I made a PR #230 (my first!). Im not sure if this is something that can be configurable or what...

**Comment by dunovank** [comment]
Thanks!
