### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by va01** [dunovank/jupyter-themes#23]
How I can uninstall whatever was installed via the pip command?

Note: I've already restored the default Jupyter theme using `jt -r`.

**Comment by PabloPsicotico** [comment]
You can remove a package with `pip uninstall <package>`, look at [this](https://pip.pypa.io/en/stable/reference/pip_uninstall/) for more details.

**Comment by va01** [comment]
Thanks -- I thought to do that but was unsure on the package name. What's the package name?

**Comment by dunovank** [comment]
jupyter-themes

On Wednesday, June 22, 2016, va01 <notifications@github.com> wrote:

> Thanks -- I thought to do that but was unsure on the package name. What's
> the package name?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dunovank/jupyter-themes/issues/23#issuecomment-227903560>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADqqzrtnlhBGuAmRudcI-JlIN253EeiHks5qOb-egaJpZM4I8OZg>
> .
>


-- 
Sent from my iPhone
