### ISSUE TITLE
Current line is white - how to change it?

### ISSUE THREAD

**Issue by richardknudsen** [dunovank/jupyter-themes#233]
Thanks for the nice package! I am having one issue though: 
Despite everything being dark with one of the dark themes, the current line is white, both in Safari and Firefox. Is there any convenient way to fix this? I have been trying for quite some time, and unsuccessfully. 
Thanks!

<img width="386" alt="screen shot 2018-02-14 at 20 53 46" src="https://user-images.githubusercontent.com/17568061/36224929-4fbe85f2-11c9-11e8-8371-824022076804.png">

**Comment by dunovank** [comment]
I haven't been able to recreate this, tried opening up a notebook in firefox and everything looked okay. Do you get the same issue if you use a different dark theme (like oceans16 instead of onedork)?

**Comment by richardknudsen** [comment]
thanks for pointing that out. I probably played around with the custom files too much. reinstalling jupyter resolved the issue.
