### ISSUE TITLE
Import error for jupyter-themes 0.18.8

### ISSUE THREAD

**Issue by meowklaski** [dunovank/jupyter-themes#236]
You need to import `glob`  [here](https://github.com/dunovank/jupyter-themes/blob/a434a290be8a9ba87b177d26eb66cb6da99d5849/jupyterthemes/jtplot.py#L66)

**Comment by dunovank** [comment]
thank you! can you double check that this is resolved in 0.18.9?

**Comment by meowklaski** [comment]
Yep! It works great now :)

While I have your attention: 

```python
from jupyterthemes import jtplot
jtplot.style()
```

is like... the greatest thing of all time. Thank you for this!

**Comment by dunovank** [comment]
lol thanks, much appreciated
