### ISSUE TITLE
oceans16 - it's hard to see red color in %%javscript mode 

### ISSUE THREAD

**Issue by hainm** [dunovank/jupyter-themes#26]
Hi

Please check this 

![o16_red](https://cloud.githubusercontent.com/assets/4451957/16498957/3e286532-3ecc-11e6-8ea3-328b6665b20c.png)

any idea how to enhance it? thanks

**Comment by dunovank** [comment]
see if the update works 

If you still have jupyter-themes (with a "-") installed:  
`pip uninstall jupyter-themes`

then:
`pip install --upgrade jupyterthemes`

**Comment by hainm** [comment]
thanks. Look good.
