### ISSUE TITLE
how to return back to original theme?

### ISSUE THREAD

**Issue by chchfin** [dunovank/jupyter-themes#262]
just like the theme shown in the attachment
![xnip2018-07-17_09-55-37](https://user-images.githubusercontent.com/31770558/42792388-976037ec-89a7-11e8-86ed-ce6ea32c20ea.jpg)

**Comment by rsaite** [comment]
It's stated in the readme:
```
# restore default theme
# NOTE: Need to delete browser cache after running jt -r
# If this doesn't work, try starting a new notebook session.
jt -r
```
Have you tried this and experienced any problem with it?

**Comment by ank0409** [comment]
Yes, it works!

**Comment by AurioPinto** [comment]
Yes, it Works, Many thanks
