### ISSUE TITLE
Toolbar missing

### ISSUE THREAD

**Issue by ainaosk** [dunovank/jupyter-themes#267]
The toggle toolbar is missing. Nothing happens when clicking View - Toggle Toolbar:
![image](https://user-images.githubusercontent.com/39031705/43505505-76429c50-9567-11e8-8e36-4c7457f4ad22.png)

When I restore the default theme, the toolbar is visible again:
![image](https://user-images.githubusercontent.com/39031705/43505665-f07fb1e2-9567-11e8-99c9-ca8d6ff3caed.png)

Any tips?

**Comment by onyekaa** [comment]
Just installed this and have the same issue.

**Comment by mattmagic149** [comment]
You can use the "-T" flag to enable the toolbar.
jt -t gruvboxd -T

**Comment by whatsupiens** [comment]
Thanks. Had the same issue and your reply helped.

**Comment by manojselvakumar** [comment]
I'm still having the issue of toolbar missing even after trying all the recommended steps. Any help is greatly appreciated, please. The toolbar doesn't seem to return even after I reset using jt -r

**Comment by ferplascencia** [comment]
It works for me. I used the anaconda prompt and I used:

jt -t chesterish
jt -t gruvboxd -T

I also closed any open jupiter notebook and launch it again. By adding the "-T" flag it will enable the toolbar.

**Comment by ldariva** [comment]
I am having the same problem. forcing the toolbar to visible (-T) is not working. Actually it is not changing the themes any more. I tried to uninstall Anaconda and reinstall it again. Didn't work. I tried to upgrade jupyter notebook. Didn't work either. Strange that it worked at first but after I realized the problem of the toolbar it stop working.

**Comment by vvthakral** [comment]
The Title Bar is missing too. That was pretty convenient to rename a file in the original jupyter theme.

**Comment by sankeashok** [comment]
run this line to enable the toolbar,  .
jt -t oceans16 -T -N

**Comment by WP-LKL** [comment]
![billede](https://user-images.githubusercontent.com/15800648/80084033-9fa08400-8556-11ea-87ab-9c0ed77d3e15.png)
Remember to activate it after adding -T option
1. !jt -t [THEME] -T
2. Refresh Page
3. View -> Toggle Toolbar

**Comment by AvinashChandrana** [comment]
for the toolbar the following command worked for me
!jt -t gruvboxd -T
however when I run the same command without '!' in front of jt , it doesn't work ,it is same for all jupyterthemes command. Can some one please help me understand why is it so ?

**Comment by WP-LKL** [comment]
> for the toolbar the following command worked for me
!jt -t gruvboxd -T
however when I run the same command without '!' in front of jt , it doesn't work ,it is same for all jupyterthemes command. Can some one please help me understand why is it so ?

@AvinashChandrana, when you prefix with "!" Jupyter executes the command outside python.
So similarly you execute "!pip install [PACKAGE_NAME]", but "jt -t gruvboxd -T" and "pip install" are not recognized by the Python interpreter.

**Comment by kapoorutkarsh7** [comment]
I have nbextensions enabled in my notebook and i have enabled the `table of contents2` extensions

When I enable toolbar it overlaps the table of contents on the left hand side of the notebook

**Comment by tensor69** [comment]
how do i enable the header though

**Comment by Andychiang13** [comment]
> I have nbextensions enabled in my notebook and i have enabled the `Table of Contents 2` extension
> 
> When I enable toolbar it overlaps the table of contents on the left hand side of the notebook

Yes! Same issue... Seems they have some bugs.

**Comment by VictorZhuMBA** [comment]
> ![billede](https://user-images.githubusercontent.com/15800648/80084033-9fa08400-8556-11ea-87ab-9c0ed77d3e15.png)
> Remember to activate it after adding -T option
> 
> 1. !jt -t [THEME] -T
> 2. Refresh Page
> 3. View -> Toggle Toolbar

Worked for me like a charm.

**Comment by Sree1259** [comment]
Finally, Got it. Thank you

**Comment by jbnetoadvocacia** [comment]
I had the same issue too, I guess it's a rookie thing! lol
Thank you guys!

**Comment by VictorSilvano** [comment]
Is there anyway to make the toolbar have a background and not overlay the code?

**Comment by hitomi-fujio** [comment]
The answers on the following page have solved the problem.
https://stackoverflow.com/questions/60798565/fix-jupyter-notebook-toolbar-with-jupyterthemes-and-table-of-contents

**Comment by 3ZadeSSG** [comment]
> ![billede](https://user-images.githubusercontent.com/15800648/80084033-9fa08400-8556-11ea-87ab-9c0ed77d3e15.png) Remember to activate it after adding -T option
> 
> 1. !jt -t [THEME] -T
> 2. Refresh Page
> 3. View -> Toggle Toolbar

worked for me, thanks

**Comment by abdulazizalmass** [comment]
works like charm. Thank you @mattmagic149

**Comment by Deanemarks1** [comment]
> jt -t oceans16 -T -N

how where? do you run this is a cell or in the terminal

**Comment by zenquiorra** [comment]
For those working in the notebook itself and don't want `cli`

```python3
import jupyterthemes as jt
jt.install_theme(theme = 'solarizedd', toolbar = True)
```
Hard refresh the page and click toggle toolbar.
