### ISSUE TITLE
Output clipped on left side (text and plots)

### ISSUE THREAD

**Issue by cdbaird** [dunovank/jupyter-themes#273]
Text output from the cells appears to be chopped off at the edge. Changing the cell width does not seem to help.

The command used here was:

`jt -t oceans16 -fs 95 -tfs 11 -nfs 115 -cellw 100%`

![screen shot 2018-09-06 at 18 03 51](https://user-images.githubusercontent.com/35960511/45173239-786d3580-b1ff-11e8-8fe5-6c055ed9aa33.png)

**Comment by souravehossain** [comment]
replace the current div.output_area with the following in the custom css file

div.output_area {
display: -webkit-box;
padding: 13px;
}

**Comment by solarqiang** [comment]
I think it's because of the cell output's folding button at the left that overlaps the text area. So in custom.css file, I changed `min-width` and `width` properties of `div.out_prompt_overlay.prompt` from `14.5ex` to `11.5ex`, and it worked. I also replaced all the occurrence throughout the file just in case of undiscovered inconsistency.

**Comment by pylin2018** [comment]
3q @solarqiang

**Comment by tdiethe** [comment]
> I think it's because of the cell output's folding button at the left that overlaps the text area. So in custom.css file, I changed `min-width` and `width` properties of `div.out_prompt_overlay.prompt` from `14.5ex` to `11.5ex`, and it worked. I also replaced all the occurrence throughout the file just in case of undiscovered inconsistency.

This only seems to work for 100%. For 95% it's still clipped until you hover over the folding button.

**Comment by tdiethe** [comment]
```
grep -n 'div.out_prompt_overlay.prompt' ~/.jupyter/custom/custom.css
1679:div.out_prompt_overlay.prompt {
1693:div.out_prompt_overlay.prompt:hover {
```

**Comment by iceonfire1** [comment]
Does anyone know how to make this change permanent, so that changing the theme with e.g. jt -t [theme] doesn't overwrite this change to the custom.css file?

**Comment by RSjakson** [comment]
> I think it's because of the cell output's folding button at the left that overlaps the text area. So in custom.css file, I changed `min-width` and `width` properties of `div.out_prompt_overlay.prompt` from `14.5ex` to `11.5ex`, and it worked. I also replaced all the occurrence throughout the file just in case of undiscovered inconsistency.

Thanks a lot, really help!!

**Comment by pskrunner14** [comment]
I changed the custom.css file, it's still not solving the issue.

**Comment by noweaver** [comment]
> div.output_area {
> display: -webkit-box;
> padding: 13px;
> }

Thank you for your guide. But in my case, your code didn't be applied. After jupyter restart, custome.css file is revoked.

**Comment by qinoq** [comment]
> > Does anyone know how to make this change permanent, so that changing the theme with e.g. jt -t [theme] doesn't overwrite this change to the custom.css file?
> 
> You can hardcode `width` and `min-width` properties of `div.out_prompt_overlay.prompt(:hover)` in `<path_to_python>/site-packages/jupyterthemes/layout/cells.less` to any value you want. Just replace `@out-prompt-min-width` with any value you want. `11.5ex` helped me.

thank you for help me to find the file.

**Comment by djchou** [comment]
Is there any way to set this via command line arguments?

**Comment by SylowVong** [comment]
> > Does anyone know how to make this change permanent, so that changing the theme with e.g. jt -t [theme] doesn't overwrite this change to the custom.css file?
> 
> You can hardcode `width` and `min-width` properties of `div.out_prompt_overlay.prompt(:hover)` in `<path_to_python>/site-packages/jupyterthemes/layout/cells.less` to any value you want. Just replace `@out-prompt-min-width` with any value you want. `11.5ex` helped me.

it worked, thank you

**Comment by heldrenata** [comment]
I found this is the easiest solution. Just paste it on top of your code to expand panels and fix the padding issue at once :)

`from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; } div.output_wrapper .output { padding-left: 14px; }</style>"))`
