### ISSUE TITLE
Full screen width results in cropped output

### ISSUE THREAD

**Issue by tdiethe** [dunovank/jupyter-themes#276]
Using solarized (light) theme with the width set to 100% (same thing happens at 90% or 95% width) results in the output being cropped:

jt -t solarizedl -T -f roboto -fs 12 -cellw 100%

![image](https://user-images.githubusercontent.com/1110560/45682242-9f006a00-bb37-11e8-8138-77317910fc0f.png)

**Comment by tdiethe** [comment]
Duplicate of #273

**Comment by czfandyslash** [comment]
Any solutions?
