### ISSUE TITLE
Export to html does not work properly with hide_code extension

### ISSUE THREAD

**Issue by dimisjim** [dunovank/jupyter-themes#277]
When trying to hide a cell of code (show only the output), and then export the notebook as html, the hided cell is still shown in the output html

Related to https://github.com/kirbs-/hide_code

**Comment by nandhaKS** [comment]
when using hide_code it's best to export notebook to html using 
jupyter nbconvert --to hide_code_html notebook_to_convert.ipynb
source: https://pypi.org/project/hide_code/0.2.0/

if you had used the default command below the hide_code will not work as expected.
jupyter nbconvert --to html notebook_to_convert.ipynb

**Comment by dimisjim** [comment]
Eventually managed to export to pdf from html, although the result is not the prettiest, using the following packages:
- wkhtmltopdf
- pandoc
- libxau6
- libxext6
- libxrender1
- xfonts-base 
- xfonts-encodings 
- xfonts-scalable
- xfonts-utils
