### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by AlphaSmartDog** [dunovank/jupyter-themes#278]
![image](https://user-images.githubusercontent.com/24935017/45916687-e15dda00-be9c-11e8-92aa-c9bad4f096f9.png)

**Comment by somexgupta** [comment]
replace the current div.output_area with the following in the custom CSS file (C:\Users\{user_name}\.jupyter\custom)

div.output_area {
display: -webkit-box;
padding: 13px;
}

**Comment by AlphaSmartDog** [comment]
Thanks very much, the problem is solved.
