### ISSUE TITLE
Code Cell Status Missing

### ISSUE THREAD

**Issue by zhanwenchen** [dunovank/jupyter-themes#279]
How can I switch on the status for each cell to the left, such as 'In [123]' after a cell has completed processing, or '*' when it hasn't?

**Comment by cyc1am3n** [comment]
You can change temporally `transparent` into any other color at `div.prompt` which is in `/.jupyter/custom/custom.css`.

**Comment by diramazioni** [comment]
@cyc1am3n ty that works! Great!
I've stumbled upon this as well. I really think transparent should not be the default.

**Comment by zhanwenchen** [comment]
@cyc1am3n Please note the correct path should be `~/.jupyter/custom/custom.css', not `/.jupyter/custom/custom.css`

**Comment by zhanwenchen** [comment]
Just to clarify for anyone new coming here, you want to edit `~/.jupyter/custom/custom.css` so that

```css
div.prompt,
.prompt {
 font-family: monospace, monospace;
 font-size: 9pt !important;
 font-weight: normal;
 color: #ff7823;
 line-height: 170%;
 padding: 0px;
 padding-top: 4px;
 padding-left: 0px;
 padding-right: 1px;
```
