### ISSUE TITLE
How to show the icons for run, insert delete like in the default version of jupyter-themes.

### ISSUE THREAD

**Issue by liyun831229** [dunovank/jupyter-themes#29]

**Comment by liyun831229** [comment]
The view->toggle toolbar/head do not actually work in chrome.

**Comment by dunovank** [comment]
What OS, version of chrome are you running? Try installing the latest release of jupyterthemes and see if it's fixed.

**Comment by ahmedsaoudi** [comment]
Same problem here. I just installed JT (so last version I guess) and I can't toggle neither the header nor the toolbar (or anything else, actually). 
Using Chrome (last stable) on Ubuntu 14.04.5.

**Comment by dunovank** [comment]
What version of Python are you running?

**Comment by ahmedsaoudi** [comment]
Sorry for the delay. It's 3.5

**Comment by dunovank** [comment]
Toolbar (run, insert delete, etc. buttons) and notebook name can be toggled via command line whenever you install a theme

```sh
#toolbar enabled (-T)
jt -t grade3 -T

#toolbar (-T) and notebook name (-N) enabled
jt -t grade3 -T -N
```
