### ISSUE TITLE
Uninstallation Instructions

### ISSUE THREAD

**Issue by Frozenfire92** [dunovank/jupyter-themes#3]
Being relatively new to Jupyter I wanted a dark theme and this was the first I found, however I noticed that I lost my toolbar upon installation of this theme. I removed the css file from where I installed it to, but the theme has persisted. In the source for the webpage it still shows custom.css, does Jupyter copy this to another directory?

**Comment by dunovank** [comment]
Have you tried emptying your browser cache? I'm not sure whether jupyter and stores an alternative copy, not to my knowledge anyway. However, look at the .css file around lines 20-35  of the css file (depending on which theme you installed). You'll see a commented instruction to comment out (or delete) the following line of code. 

div#maintoolbar {
    display: none !important;
}

deleting or commenting out this line will restore the toolbar.

**Comment by Frozenfire92** [comment]
Emptying the browser cache didn't do it. I recopied the css file, changed that line, but it seems to be using the cached version that Jupyter has saved somewhere previously :confused: 

I'll keep looking around because I really dig this theme and hopefully can help someone else.

Thanks for the quick response!

**Comment by Frozenfire92** [comment]
I have figured it out, it turns out Jupyter copies stuff from you `~/.ipython/` directory to `~/.jupyter/` I removed `~/.jupyter/custom/` and this caused it to recopy the new css file from `~/.ipython/`

Maybe the install instructions should just cp to the `.jupyter` folder?

I found this from `jupyter --config-dir`

**Comment by dunovank** [comment]
Ah interesting... Thanks so much for following up, I had no idea about this. I'll update the instructions when I have a minute.

Thanks again!
kd

**Comment by dunovank** [comment]
Just wanted to post an update here, cl toggle of the toolbar should be fixed now.
