### ISSUE TITLE
Toolbar background not visible

### ISSUE THREAD

**Issue by baibai25** [dunovank/jupyter-themes#310]
Hi! 
See the attached images.
![_2018-11-30_21-23-27](https://user-images.githubusercontent.com/32119295/49306104-9d2e2c00-f514-11e8-9b6e-524d51c58a5f.png)
![_2018-11-30_21-23-45](https://user-images.githubusercontent.com/32119295/49306110-a0291c80-f514-11e8-9885-401fd33b4601.png)

I upgraded to the latest version v0.20.0.
When scrolling, the background of the toolbar disappears.

I had set following command:
`jt -t chesterish -T -N -fs 14 -vim -cellw 90%`

Thank you

**Comment by hellenlima** [comment]
Same here with:
`jt -t chesterish -T -N -kl -ofs 10 -tfs 11`

**Comment by arthurire** [comment]
search 
`div#maintoolbar`
then, remove
`position:absolute; `
![image](https://user-images.githubusercontent.com/27836456/54096226-f2b48780-43e5-11e9-827c-d6d260fb365d.png)
@hellenlima @baibai25

**Comment by baibai25** [comment]
Thank you @arthurire 
I'm using JupyterLab now. I will check it.

**Comment by jraviotta** [comment]
Thank you @arthurire . Your fixed worked for me.

**Comment by baibai25** [comment]
Thank you again @arthurire. I suggest that you should send pull request.

Should I close this issue?

**Comment by arthurire** [comment]
> Thank you again @arthurire. I suggest that you should send pull request.
> 
> Should I close this issue?

It's up to you.

I don't know how the author generates those css files exactly so I did not send a pull request.

**Comment by hellenlima** [comment]
@arthurire's fix worked for me too. thank you!

**Comment by TheCamilovisk** [comment]
Some may have noted that when you change the theme, the toolbar background will be transparent again.
To make the the background transparent permanently, one should edit this file instead:
`<python-site-packages-path>/jupyterthemes/layout/notebook.less`.
