### ISSUE TITLE
Can't find nbextension after installation

### ISSUE THREAD

**Issue by landmann** [dunovank/jupyter-themes#313]
I have installed the preferred dark style `jt -t onedork -fs 95 -altp -tfs 11 -nfs 115 -cellw 88% -T`, and now my `nbextension` has disappeared from the menu bar :( any thoughts? I have attempted to reinstall the nbextension app [here](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/install.html) and [configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator), but no dice.

**Comment by landmann** [comment]
Hey! I am actually getting no errors on the terminal - it simply doesn't appear on Jupyter.

**Comment by Miladiouss** [comment]
I have the same problem (Ubuntu, Anaconda 3); the installed extensions under the toolbar are missing.

**Comment by landmann** [comment]
It's all good - just click on `Edit -> nbextensions config` and it'll take you straight there.

**Comment by kumarnikhil936** [comment]
> Hey landmann, I had the same issue.
> Did you run `jupyter contrib nbextension install --user`?
> And are you getting any 403 errors in your terminal?

This "--user" argument solved this issue for me
