### ISSUE TITLE
'__array_function__'

### ISSUE THREAD

**Issue by Penn000** [dunovank/jupyter-themes#317]
Hello，when I run jt command,  it arises an error:

> AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'

is it because my Numpy not new? my Numpy version is 1.16.0

Thanks!

**Comment by jharonfe** [comment]
This may be a numpy issue. Read [here](https://github.com/numpy/numpy/issues/12736).

**Comment by Penn000** [comment]
Thank you, I remove `~/.local/lib/python3.6/site-packages/numpy` and then solved the problem
