### ISSUE TITLE
add minimal tests

### ISSUE THREAD

**Issue by hainm** [dunovank/jupyter-themes#32]
released versions (e.g v0.9.1) and master have a series of bugs that prevents install the new theme. (e.g TypeError due to string format #31,). May be you can add travis continuous integration for different python versions?

**Comment by dunovank** [comment]
Yeah this is definitely on my todo list. Will prioritize. As an aside, are you able to install themes on the latest version?

**Comment by hainm** [comment]
> As an aside, are you able to install themes on the latest version?

Unfortunately No (including master branch)

**Comment by dunovank** [comment]
marking complete
