### ISSUE TITLE
doesn't work nicely with ipywidgets5

### ISSUE THREAD

**Issue by hainm** [dunovank/jupyter-themes#33]
hi, please see below.

- onedork

![jt](https://cloud.githubusercontent.com/assets/4451957/17267060/6a35ed74-55cf-11e6-90a0-791a60e840c0.png)

- default Jupyter

![jt2](https://cloud.githubusercontent.com/assets/4451957/17267084/a07623cc-55cf-11e6-99ac-5d72d134d8c2.png)

**Comment by hainm** [comment]
somes ipywidgets 5 notebooks: https://github.com/ipython/ipywidgets/tree/master/docs/source/examples

**Comment by dunovank** [comment]
Checkout the update, background color should be fixed

**Comment by hainm** [comment]
thanks.
