### ISSUE TITLE
Total White Screen 

### ISSUE THREAD

**Issue by mlabarrere** [dunovank/jupyter-themes#330]
Hello,

After installing Jupyter-Theme with `pip install jupyterthemes`, and starting the kernel after the command `jt -t chesterish`. The _Home_ page at my `http://localhost:8888/tree` gets to the color of the theme, but nothing is printed, no menus, just a solid colored page, and I'm not able to interact with it anymore. 

I've tried:
1. Reset with `jt -r`, it gets the empty page white
1. Uninstall `jupyterthemes`, reinstall it, and remove it totally
2. Uninstall and reinstall `jupyter` & `notebook`, as well as the remaining folders manually
3. Clearing my browser cache, as well as privates windows, and different browsers
4. Uninstalling Python, and replace it in an other PATH

Nothing worked, the _Home_ page remains white after the full Python reinstall.

My configuration:
1. Windows 10
2. Python 3.7
3. All installs are made with pip 19

**Comment by dunovank** [comment]
Wow this sounds terrible (very sorry for the headache). 

If you can open up a ipython or python session, what is the output of the following lines
```python
from jupyter_core.paths import jupyter_config_dir, jupyter_data_dir
print('CORE: {}'.format(jupyter_config_dir()))
print('DATA: {}'.format(jupyter_data_dir()))
```

**Comment by dunovank** [comment]
Are there any files/folders in `jupyter_config_dir()` ? If so what are they?

**Comment by mlabarrere** [comment]
Hello @dunovank,
Many thanks for the quick reply.

The outputs of the two commands are: `CORE: C:\Users\mlabarrere\.jupyter` & `DATA: C:\Users\mlabarrere\AppData\Roaming\jupyter`

Unfortunately, the hidden folder `.jupyter` does not exist.

Furthermore, the `AppData\Roaming\jupyter` folder contains one sub folder named `runtime`, with three files:
1. `nbserver-13504.json`
2. `nbserver-13504-open.html`
3. `notebook_cookie_secret`

The .json is:
```javascript
{
  "base_url": "/",
  "hostname": "localhost",
  "notebook_dir": "C:\\Users\\mlabarrere",
  "password": false,
  "pid": 13504,
  "port": 8888,
  "secure": false,
  "token": "XX",
  "url": "http://localhost:8888/"
}
```

And the .HTML one is:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="1;url=http://localhost:8888/tree?token=XX" />
    <title>Opening Jupyter Notebook</title>
</head>
<body>
<p>
    This page should redirect you to Jupyter Notebook. If it doesn't,
    <a href="http://localhost:8888/tree?token=XX">click here to go to Jupyter</a>.
</p>
</body>
</html>
```

I removed the token ID by _XX_ for clarity

**Comment by wangtianrui** [comment]
I have the same problem.
The outputs of the two commands are:
```txt
CORE: C:\Users\ScorpioMiku\.jupyter
DATA: C:\Users\ScorpioMiku\AppData\Roaming\jupyter
```

**Comment by mlabarrere** [comment]
Hey guys,

I found out a solution, you need to downgrade the _notebook_ package. To do so:
```bash
pip uninstall notebook
pip install notebook==5.7.5
```

Launch your kernel with the classic `jupyter notebook` command, normally you'll still see the white page. Do `Ctrl+Shift+R` to reload without cache, and voilà!

I guess the problem wasn't related to the `jupyterthemes` package, the `notebook` one must have been updated in the installation process, but `jupyterthemes` has nothing to do with the white screen page.

Thanks for your help guys!

**Comment by mlabarrere** [comment]
Additional note:

If you have kernel issues, don't forget to downgrade the `tornado` package to the fifth version with:
```bash
pip uninstall tornado
pip install tornado==5.1.1
```
