### ISSUE TITLE
Getting the plot to show in front of the grid 

### ISSUE THREAD

**Issue by TheChanRProject** [dunovank/jupyter-themes#333]
Hi Kyle, 

I noticed that when I make a plot using a jtplot theme, the plotted data is being shown behind the grid lines. Is there a way in jtplot to make the data show in front of the grid lines so the data is more prominent? Of course it's possible to just set the grid=False, but the grid is nice and I would love to know if it's possible to just set the lines to be in the back of the plotted data. 

Thank you very much in advance,

Rishov

**Comment by RyanWalker19** [comment]
Hi Rishov,

I had the same question and accidentally found a somewhat kludgy solution while goofing around deciding what plot styles I like. If you import seaborn and do sns.set() before using jtplot.style(), the grid ends up behind the plot the way we both want it. I'm not good enough to say why this works, but I'm happy with the results.

Best,
Ryan

**Comment by TheChanRProject** [comment]
@RyanWalker19 , I am like super late in replying to this. 

You are absolutely right. After using sns.set() , the plot does go over the grid. I haven't looked into the internals as I've been very busy since I opened this issue. 

Thank you very much for your comment. This issue can be successfully closed.
