### ISSUE TITLE
can not see the button, only see its description

### ISSUE THREAD

**Issue by hainm** [dunovank/jupyter-themes#35]
Hi

I only tested with `ipywidgets5`

yours

![button_jt](https://cloud.githubusercontent.com/assets/4451957/17283422/1552c114-577e-11e6-9e14-464a0ee019be.png)

original

![button_jt_original](https://cloud.githubusercontent.com/assets/4451957/17283427/1be620d4-577e-11e6-9ea0-6af72cc65798.png)

code

```python
import ipywidgets

b0 = ipywidgets.Button(description='hello')
b1 = ipywidgets.Button(description='there')

ipywidgets.Box([b0, b1])
```

**Comment by dunovank** [comment]
any better in 0.10.3?

**Comment by dunovank** [comment]
Scratch that (if you're using 3.5), I forgot to update the compiled theme files in 0.10.3, new compiled versions are included in 0.10.4

**Comment by hainm** [comment]
look nicer. thanks. Would it be possible to make the button more "noticeable"?  

![relayout](https://cloud.githubusercontent.com/assets/4451957/17386900/cc83d9f0-59bc-11e6-81a2-1050c2cca794.png)


default theme

![old](https://cloud.githubusercontent.com/assets/4451957/17386934/10fe2a90-59bd-11e6-896d-1c5ba4a4b51a.png)

**Comment by hainm** [comment]
but overall I think it's great,

**Comment by dunovank** [comment]
thanks. Looks like the tabs could use some work. I'll play around with it when I have some spare time. Not sure when that'll be but I'll definitely put it on the todo list

**Comment by hainm** [comment]
yeah, take your time, there's no rush. thanks.

**Comment by hainm** [comment]
ah, can you add your credit in the compiled css file too?

**Comment by dunovank** [comment]
Closing this one out for now. Thanks for all the feedback @hainm !
