### ISSUE TITLE
Set-up Fastai (Deep Learning Library) in the Jupyter Notebook 

### ISSUE THREAD

**Issue by AurioPinto** [dunovank/jupyter-themes#363]
## Troubleshooting:
 Currently, I am starting my course on deep learning from fast.ai, and having set-up most of the environment on my machine. I can use the fastai dataset when I run my code from the terminal, but when I try to use it on the jupyter notebook I am getting the following error message:

![Screenshot from 2019-10-04 18-22-19](https://user-images.githubusercontent.com/34268278/66200907-a65bcc80-e6d4-11e9-8725-c5fa095b2f63.png)

**Comment by AurioPinto** [comment]
I actually solved this problem now, you can find the solution on the fastai.com/ Documentation to run the library in the jupyter notebook, and see the following commands here and the fig of my coding running
![Screenshot from 2019-10-05 16-19-23](https://user-images.githubusercontent.com/34268278/66267971-8cec8900-e86a-11e9-9345-3fdf26e36145.png)

**Comment by andrhua** [comment]
Amazing issue, bug that is not even related to Jupyter, and after 2 weeks it is still open, but I guess, maintainer had dumped it already...

**Comment by AurioPinto** [comment]
Indeed @andrhua, I also read their documentation and I found the steps to run fastai library on Jupiter notebook, perhaps that was the issue

**Comment by DhruvaSambrani** [comment]
Please close the issue if you have solved it

**Comment by AurioPinto** [comment]
@DhruvaSambrani Thank you for the reminder!
