### ISSUE TITLE
smaller fontsize for Tab's titile + larger font size for Button label?

### ISSUE THREAD

**Issue by hainm** [dunovank/jupyter-themes#37]
.. relatively to font size of the code.

What do you think?

yours
![jt](https://cloud.githubusercontent.com/assets/4451957/17304606/7a68f78c-57f4-11e6-8155-eca371ef6a8b.png)

original
![jt_original](https://cloud.githubusercontent.com/assets/4451957/17304610/7e451d18-57f4-11e6-99ab-d708f482b09a.png)

**Comment by dunovank** [comment]
Fixed. See also #35 and #53
