### ISSUE TITLE
How can I change the strange color in a dark theme?

### ISSUE THREAD

**Issue by PKUFlyingPig** [dunovank/jupyter-themes#378]
I chose  a dark theme, but when I enter a cell and begin to write codes, the color of the cell becomes bright, and it makes me feel hard to see the codes.Can I change this ?
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/60659728/75630971-c793fb00-5c29-11ea-857c-2239be27de47.png">

**Comment by mpaliwoda** [comment]
Hi @PKUFlyingPig, looks like you're using Vim `nbextension` - I've had the same problem and found out [in this old issue](https://github.com/dunovank/jupyter-themes/issues/41#issuecomment-241935758) that `jupyter-themes` support `-vim` flag. 

Try adding it to a command you've executed to set your current theme (as executing bare `jt -vim` will override the rest of your config with default jupyter theme) - you want it to look something like 
```bash
jt -t oceans16 -f roboto -fs 12 -vim
```
judging from the screenshot you provided.

**Comment by PKUFlyingPig** [comment]
Thank you so much ! I have been suffered for the strange color for weeks. It does work for me. Thank you again!
