### ISSUE TITLE
JupyterThemes does not allow changing notebooks filename inside of notebook

### ISSUE THREAD

**Issue by jbrambleDC** [dunovank/jupyter-themes#39]

**Comment by hainm** [comment]
what do you mean 'do not allow'?

**Comment by dunovank** [comment]
Ctrl-Shift-P (open the command palette) and start typing rename and you'll see an option for rename notebook

**Comment by hainm** [comment]
or choose

`File --> Rename`

**Comment by jbrambleDC** [comment]
yeah all of that works. Sorry I should be more specific, the stock jupyter theme has the NB title in a textbox at the top left, one can type in the box and change the title. would be nice to add that back?

**Comment by dunovank** [comment]
no worries, I'm pretty swamped with other projects right now but I'll put that on the list of options to include in the next release

**Comment by dunovank** [comment]
jk (decided to go ahead and release with this added in...) hopefully it works... I'm tired. 

to install theme with filename and jupyter logo visible:

```
jt -t grade3 -N -J
```

**Comment by jbrambleDC** [comment]
Thats awesome! Ill close this!
