### ISSUE TITLE
command palette is white

### ISSUE THREAD

**Issue by karimelgazar** [dunovank/jupyter-themes#394]
I use Onedork Theme and everything is ok but the command palette is white. what's the problem?

![235432-2020-05-31](https://user-images.githubusercontent.com/37200364/83363689-9b5c5780-a39b-11ea-91c5-99f48cfbf184.png)

**Comment by srggrs** [comment]
I can confirm with theme chesterish. Here is my env details:
```bash
Python 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0] :: Anaconda, Inc.
 - - - - - - - - - - - - - - - - - - - - - - - - - - -
ipython=7.15.0=py37_0
jupyter=1.0.0=py37_7
jupyter_client=6.1.3=py_0
jupyter_console=6.1.0=py_0
jupyter_contrib_core=0.3.3=py_2
jupyter_core=4.6.3=py37_0
jupyter_nbextensions_configurator=0.4.1=py37_0
jupyterthemes=0.20.0=py_1
nbconvert=5.6.1=py37_0
nbformat=5.0.7=py_0
notebook=6.0.3=py37_0
```

**Comment by richardso21** [comment]
This problem persists with all themes, regardless.

I found the solution: **_downgrade_** the `notebook` package to be at `5.7.9` or below. It seems the new major release made some changes to the command palette which broke the theming. Can confirm this downgrade won't break anything (jupyter, jupyterlab, etc.), as far as I know.

**Comment by srggrs** [comment]
@richardso21 I can confirm that downgrading will solve the issue

**Comment by AnirvanB** [comment]
**`One year on this is still an issue!!`**

Latest notebook version is around ~6.4.0. Doesn't make sense downgrading to 5.7.9. Any chance this would be fixed?
