### ISSUE TITLE
-T -N (not) working as intended?

### ISSUE THREAD

**Issue by DocMinus** [dunovank/jupyter-themes#412]
I only see the menu bar and the kernel name, at best the notebook name with these switches.
No toolbar.
For any of the themes.
I use for e.g.
`jt -t solarizedd -T -N`
(also monkai, etc)
Is this as intended?

**Comment by velikod** [comment]
For me `-T` does the trick for the toolbar. Are you sure you refreshed your browser?

**Comment by DocMinus** [comment]
> For me `-T` does the trick for the toolbar. Are you sure you refreshed your browser?

Yes. Then again, it can be activated in the menu, so, maybe it really is just me.
