### ISSUE TITLE
Jupyter notebook not showing In[] / Out[]

### ISSUE THREAD

**Issue by genecell** [dunovank/jupyter-themes#417]
Hi, I was using the following setting:

`jt -t onedork -f fira -fs 115 -altp -tfs 11 -nfs 115 -dfs 10 -ofs 10 -cellw 90% -T -N -kl
`
but I found the In[]/Out[] which shows the order of codes running is gone, and the information about the order of running codes is important.

Thanks in advance!

**Comment by sirandluke** [comment]
The problem is because of the `-altp` flag, which removes the numbers. Remove it and you will be able to see them again. If it doesn't work, try reseting the theme first and reapply your preferences:
`jt -r
jt -t onedork -f fira -fs 115 -tfs 11 -nfs 115 -dfs 10 -ofs 10 -cellw 90% -T -N -kl`

**Comment by genecell** [comment]
Thanks! I solved the problem with your kind help!

**Comment by Lord-V15** [comment]
Hey. Shouldn’t this be closed? It’s not much of an issue anymore.

**Comment by velikod** [comment]
> 
> 
> Hey. Shouldn’t this be closed? It’s not much of an issue anymore.

@genecell Please close the issue
