### ISSUE TITLE
lesscpy is now Python 3.5 compatible

### ISSUE THREAD

**Issue by meowklaski** [dunovank/jupyter-themes#43]
Python 3.5 users should be able to modify default settings, once you upgrade the package's install of lesscpy

**Comment by dunovank** [comment]
fantastic thanks for heads up!

**Comment by dunovank** [comment]
Still waiting for 3.5 compatibility to make it's way into the official release on pypi. I've opened an issue [here](https://github.com/lesscpy/lesscpy/issues/87) asking when to anticipate an updated official release.

**Comment by meowklaski** [comment]
Cool, thanks for the update!

**Comment by meowklaski** [comment]
As far as I can tell, lesscpy 0.11.1 (via pip) is working with 3.5

**Comment by OmanF** [comment]
Accodring to PyPI, `lesscpy` is, as of 04.10.16, at version 0.12 and officially supporting Python 3.5 (if I'm reading PyPI page correctly, that is).

**Comment by dunovank** [comment]
Thanks for the updates, just released a new version that should (hopefully) allow full functionality for Python3.5 users. Leaving this issue open for now in case any problems arise.

**Comment by OmanF** [comment]
Can only speak for myself, of course, but, works perfectly on Ubuntu 16.04 with Python 3.5.2.
(Screenshot showing `oceans16` theme with `FiraCode` font).

Thanks for making this plugin, generally, and making it fully functional with Python 3.5+!

![screenshot_2016-10-06_22-20-24](https://cloud.githubusercontent.com/assets/7848797/19167374/0eb2ce10-8c14-11e6-96d7-ef60a832de9d.png)

**Comment by dunovank** [comment]
Totally, glad it's working!

**Comment by dunovank** [comment]
I'll close this out then.
