### ISSUE TITLE
How to apply theme correctly to Jupyter Lab?

### ISSUE THREAD

**Issue by klazaj** [dunovank/jupyter-themes#437]
I type `jt -t chesterish` in the terminal (OS is Ubuntu 20.04), and then change the theme on the interface: _Settings -> JupyterLab Theme > @dunovank/jupyterlab_legos_ui)_. 
Unfortunately, the theme doesn't change from light to dark. The only changes made are some font colors, and that's it. Am i doing something wrong?

**Comment by dunovank** [comment]
Sorry for the confusion, the @dunovank/jupyterlab_legos_ui is a completely separate package that is compatible with jupyter lab. However, none of the themes in the `jupyter-themes` repo are available in jupyterlab. 

You installed the jupyter lab theme correctly, it's a light theme and some minor ui tweaks but that's it for now. 

I'm potentially going to continue  building more themes for jupyter lab but not sure how soon the next one will be ready. I am planning for the next one to be a dark theme so I will post another update in this repo when that happens.
