### ISSUE TITLE
Active cell is too bright in dark themes

### ISSUE THREAD

**Issue by iiey** [dunovank/jupyter-themes#441]
Installed new environment in conda:
```sh
conda create -n jupyter -c conda-forge notebook
pip install jupyterthemes
pip install --upgrade jupyterthemes
```

* **environment**
```sh
s$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : not installed
ipython          : 7.21.0
ipykernel        : 5.5.0
jupyter client   : 6.1.12
jupyter lab      : 3.0.10
nbconvert        : 6.0.7
ipywidgets       : not installed
nbformat         : 5.1.2
traitlets        : 5.0.5

$ firefox --version
Mozilla Firefox 78.9.0esr
```

* **command**
```sh
jt -t onedork -T
```
Problem is the same for any themes.

<img src=https://user-images.githubusercontent.com/18628392/111435555-3ba02480-8701-11eb-8858-51a486c6b49c.jpg  width=50%>

How can we fix it? Thank you in advance!

**Comment by Kipparis** [comment]
Use `-vim` option while changing theme. For example `jt -t onedork -vim -T`

**Comment by iiey** [comment]
Thank you very much. It works out for me.
It makes sense to have extra warning about `-vim` in README
