### ISSUE TITLE
The last character being cut-off or truncated

### ISSUE THREAD

**Issue by lazypandabear** [dunovank/jupyter-themes#461]
The last character of the text in the cell is truncated when the characters reach the end. Please see the image below. The square bracket is there but cannot be seen. 

![image](https://user-images.githubusercontent.com/30072448/182307661-f3c81b2d-d288-4945-9163-06c5b006190d.png)

**Comment by John-Miller12** [comment]
I have experienced the same issue
`notebook 6.4.5` (via anaconda)
`jupyterthemes 0.20.0` 
`chrome 104.0.5112.101 (official build)`

`notebook` is running out of the box, no widgets, extensions, code magic or anything

replicated in both `solarizedd` and `onedork`

**Comment by PIANNOion** [comment]
It might help if you change the setting of "div.CodeMirror-lines" in the custom CSS file ( .jupyter\custom\custom.css)

In "div.CodeMirror-lines", set the "padding-left" parameter smaller, i set it to zero

<img width="311" alt="original"  src="https://user-images.githubusercontent.com/78261339/198413355-e69728f3-23cc-42e0-be80-c3ada24e39be.PNG">
before adjustment

![adjustment](https://user-images.githubusercontent.com/78261339/198414031-da20c21b-131a-4d55-ba89-dced9d06b2bf.png)

adjustment

![after adjustment](https://user-images.githubusercontent.com/78261339/198414145-133d8596-2961-4681-9548-13e07555d677.png)
after adjustment

**Comment by lazypandabear** [comment]
Thank you!
