### ISSUE TITLE
Themes only being applied to the cell

### ISSUE THREAD

**Issue by CVisler** [dunovank/jupyter-themes#475]
Themes are being registered in the ~/.jupyter/custom files but for some reason they only apply to the notebook cells rather than the whole thing. 
Some of the lilghter themes look strange as well with the font color being light like the background so it is unreadable

![Screenshot from 2023-11-29 11-03-34](https://github.com/dunovank/jupyter-themes/assets/128059017/2b628977-1443-47c9-9ab7-b2c15147a217)

**Comment by Saka30** [comment]
Hi man, how did you solve this issue ?
