### ISSUE TITLE
widget is not shown

### ISSUE THREAD

**Issue by hainm** [dunovank/jupyter-themes#53]
Hi,

I got trouble with `v0.11.8`. Our widget is not shown.

![no_widget](https://cloud.githubusercontent.com/assets/4451957/17952376/d76ad644-6a37-11e6-9239-ab7886600924.png)

The display is similiar to this: https://github.com/dunovank/jupyter-themes/issues/35

![relayout](https://cloud.githubusercontent.com/assets/4451957/17386900/cc83d9f0-59bc-11e6-81a2-1050c2cca794.png)

**Comment by dunovank** [comment]
Hey sorry about that, see if it's fixed in 0.11.9. 

As an aside, I install nglview but couldn't run nglview.demo(gui=True). I think the error was "Module has no attribute demo". But I was able to recreate the failed display by running 

```python
import nglview
view = nglview.show_pdbid("3pqr")  # load "3pqr" from RCSB PDB and display viewer widget
view
```

Seems to be fixed now but let me know if it gives you any more issues. What am I missing with regards to running the demo? I installed using pip. (version 0.5.1 I think).

Super cool widget by the way.

**Comment by hainm** [comment]
It does not work for me although I tried to clean my cache.

> I install nglview but couldn't run nglview.demo(gui=True)

ah, probably that 'demo' is in master branch. The released version is quite outdated and we don't have new release version yet.

Can you try `nglview` master branch? We require user to install `ipywidgets >= 5.0` now (nglview `0.5.1` only work with ipywidget 4`)

> Super cool widget by the way.

thanks. It plays very nicely with your theme package.

**Comment by hainm** [comment]
minor point: Trying to reset them but getting 

````python
$ jt -r
Traceback (most recent call last):
  File "/home/haichit/anaconda3/bin/jt", line 11, in <module>
    sys.exit(main())
  File "/home/haichit/anaconda3/lib/python3.5/site-packages/jupyterthemes/__init__.py", line 87, in main
    reset_default(verbose=True)
NameError: name 'reset_default' is not defined

haichit@~/test $ python -c 'import jupyterthemes as jt; print(jt.__version__)'
0.11.9

```

**Comment by dunovank** [comment]
damn... thanks for catching that. I obviously haven't put too much time into the build tests... need to get on that soon. Will push an updated release to pypi soon.

**Comment by dunovank** [comment]
any luck with 12.1?

**Comment by hainm** [comment]
sadly no.

**Comment by dunovank** [comment]
wow weird.. sorry, not sure what the deal is. Will look into it when I have some more time.

**Comment by hainm** [comment]
have you tested with py35 too?

**Comment by hainm** [comment]
just tested with py2 and got the same issue. I will try in another computer tomorrow.

**Comment by hainm** [comment]
uhm, I think it works now. caching is evil. thanks.

**Comment by hainm** [comment]
![w](https://cloud.githubusercontent.com/assets/4451957/17956598/25ccd5c8-6a59-11e6-955c-f07635eb1ecb.png)

**Comment by dunovank** [comment]
whew, good to know
