### ISSUE TITLE
prompt input_prompt not aligned with cell

### ISSUE THREAD

**Issue by fbrundu** [dunovank/jupyter-themes#60]
Hi,
using `grade3` theme (I haven't tested others), the text in div `prompt.input_prompt` is not aligned with the text of the cell. This gets worse also when I change font size.
Maybe it's a padding problem. I attached a screenshot.

![screenshot from 2016-10-06 11-43-26](https://cloud.githubusercontent.com/assets/697622/19147873/784db0ec-8bba-11e6-80d0-c05dcbbfb682.png)

Thanks,
Francesco

**Comment by dunovank** [comment]
Can you check if it's fixed in latest version?

**Comment by fbrundu** [comment]
Yes, fixed. Thanks :)
