### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by BlakeTrebelhorn** [dunovank/jupyter-themes#64]
This isn't so much of an issue, but a suggestion. I'm not sure if this is doable already, but it would be nice to set the cell width to be a % of the width, so it resizes dynamically when the window is resized. I've been using this code in my custom.css to do so(which I've found on the internet):

Make the notebook cells take almost all available width
`.container {width: 99% !important;}`

Prevent the edit cell highlight box from getting clipped; \* important so that it also works when cell is in edit mode
`div.cell.selected {border-left-width: 1px !important;}`

I've just added it to the bottom of the custom.css made by jt and it works well.
Also I want to say thanks for this, it's really awesome!

**Comment by dunovank** [comment]
Hey, sorry I forgot about this suggestion. The latest release includes this capability, using the argument `-cellw 99%`
