### ISSUE TITLE
When exporting to HTML with nbconvert, syntax highlighting is not preserved

### ISSUE THREAD

**Issue by rubik** [dunovank/jupyter-themes#66]
One can convert notebooks to HTML with the command:

```
$ jupyter nbconvert notebook.ipynb
```

Strangely enough, the CSS for the cells, titles, etc. is preserved in the output, but not the CSS responsible for the syntax highlighting. Instead, the IPython default is used, which doesn't pair well with the other themes.

Do you have any clues for the fact that some CSS is exported and some is not? Thanks

**Comment by carlthome** [comment]
Perhaps contribute a pr that fixes this?

**Comment by dunovank** [comment]
yeah, I think this is actually a more complex issue than it would seem. I won't have the time nor the expertise to add this functionality but as @carlthome suggested, feel free to submit a PR. Thanks.
