### ISSUE TITLE
The jupyter-themes pack does not affect the Terminal at all and affects text editor partially

### ISSUE THREAD

**Issue by RomanovMikeV** [dunovank/jupyter-themes#68]
The Terminal isnot affected by themes at all (still remains white-and-black)
The TextEditor is themed only in the field with the text itself and the header is also themed, but the frame around remains white together with line numbers.

**Comment by dunovank** [comment]
This package is specifically meant with jupyter notebooks. For applying themes to your terminal, I reccommend using [iterm](https://www.iterm2.com/version3.html) and [ohmyzsh](https://github.com/robbyrussell/oh-my-zsh).

**Comment by dunovank** [comment]
Also, I just found this cool repo where someone ported these themes to hyperterm https://www.npmjs.com/package/hyperterm-grade3

**Comment by RomanovMikeV** [comment]
I mean the Terminal and the Text Editor that may be summoned from the jupyter notebook tree (i.e. the ones accessible through the browser: You may click on the New button and select a Terminal notebook and the same way with Text Files)

**Comment by RomanovMikeV** [comment]
![2016-10-17 19 44 12](https://cloud.githubusercontent.com/assets/1107320/19446601/920d6d08-94aa-11e6-8fcd-5b9c46cf8489.png)
![2016-10-17 19 43 59](https://cloud.githubusercontent.com/assets/1107320/19446607/94df3408-94aa-11e6-96a5-a90a51e6a96e.png)

**Comment by dunovank** [comment]
this should be fixed in the latest release

```sh
# install/upgrade to latest version
pip install --upgrade jupyterthemes
```
