### ISSUE TITLE
Windows install issue

### ISSUE THREAD

**Issue by mattytrentini** [dunovank/jupyter-themes#7]
Heya Kyle,

Love the look of your themes but am having trouble installing them on Windows using Anaconda (2.4.0 64 bit). I'm running this in cmd.exe but I've also tried it using Git Bash (2.7.0 64 bit) with the same result.

    >pip install git+https://github.com/dunovank/jupyter-themes.git
    Collecting git+https://github.com/dunovank/jupyter-themes.git
      Cloning https://github.com/dunovank/jupyter-themes.git to c:\users\matt~1.tre\appdata\local\temp\pip-hmy4xr-build
    Collecting sh (from jupyter-themes==0.1)
      Using cached sh-1.11.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "c:\users\matt~1.tre\appdata\local\temp\pip-build-v_m6bu\sh\setup.py", line 4, in <module>
            import sh
          File "sh.py", line 37, in <module>
            support." % __version__)
        ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in c:\users\matt~1.tre\appdata\local\temp\pip-build-v_m6bu\sh

But pbs is already installed and appears to be the correct version:

    >pip install pbs
    Requirement already satisfied (use --upgrade to upgrade): pbs in c:\anaconda\lib\site-packages

    >pip show pbs
    ---
    Metadata-Version: 2.0
    Name: pbs
    Version: 0.110

I've only take a quick look but here's what seems to be happening...hoping you can shed more light on this!

So, although the [documentation](http://amoffat.github.io/sh/) doesn't mention platform compatibility, the internet seems to suggest ([1](http://www.makeuseof.com/tag/move-shell-scripts-sh-py-awesome/), [2](http://stackoverflow.com/questions/28618906/porting-sh-1-11-based-code-to-windows), [3](http://www.blog.pythonlibrary.org/2014/08/07/the-new-sh-package-a-subprocess-wrapper/)) that sh.py doesn't support Windows. It seems that the installer is aborting as soon as it detects that we're trying to install a non-Windows supported module on Windows. 

I think using pbs as an alternative is a red herring; the project is no longer supported. And you'd have to change your code to use pbs anyway.

However, it seems that the only use of sh here is for cp (in `__init__.py`). You're already using shutil - which *is* cross-platform - and also contains a copy function. Would you be able to change to using [shutil.copy](https://docs.python.org/2/library/shutil.html#shutil.copy) instead of sh.cp?

**Comment by dunovank** [comment]
Hi, thanks for the kind words. 
I just replaced all occurences of sh.cp with shutil.copy. It still works on linux, haven't tested on osx or windows yet. Would you mind testing it out and checking back in with the results?

**Comment by mattytrentini** [comment]
Tried installing with pip but it still fails. Your changes to `__init__` look good but `setup.py` still lists `sh` as a dependency which I think is the problem. Can you remove it as a dependency and I'll try again?

[If I get a spare 10 minutes I'll fork and try it myself, I'm just in the thick of it right now!]

**Comment by dunovank** [comment]
same here... grant writing season... I merged your pull request, I assume you got it working on Windows? (I saw you reopened the issue so just wanted to double check)

**Comment by mattytrentini** [comment]
I was a little premature... ;)

The installer completes without errors now however the `.jupyter-themes` directory isn't created in the right place. It should, but doesn't, appear in the user directory. Here's the installer output:

(`d:\projects\jupyter-themes\` is the location of the git repo checkout)

    D:\projects\test\jupyter>pip install -vvv -e d:\projects\jupyter-themes\
    Obtaining file:///D:/projects/jupyter-themes
      Running setup.py (path:D:\projects\jupyter-themes\setup.py) egg_info for package from file:///D:/projects/jupyter-themes
        Running command python setup.py egg_info
        running egg_info
        writing jupyter_themes.egg-info\PKG-INFO
        writing top-level names to jupyter_themes.egg-info\top_level.txt
        writing dependency_links to jupyter_themes.egg-info\dependency_links.txt
        writing entry points to jupyter_themes.egg-info\entry_points.txt
        warning: manifest_maker: standard file '-c' not found

        reading manifest file 'jupyter_themes.egg-info\SOURCES.txt'
        writing manifest file 'jupyter_themes.egg-info\SOURCES.txt'
      Source in d:\projects\jupyter-themes has version 0.1, which satisfies requirement jupyter-themes==0.1 from file:///D:/projects/jupyter-themes
    Installing collected packages: jupyter-themes
      Running setup.py develop for jupyter-themes
        Running command C:\Anaconda\python.exe -c "import setuptools, tokenize; __file__='D:\\projects\\jupyter-themes\\setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps
        running develop
        running egg_info
        writing jupyter_themes.egg-info\PKG-INFO
        writing top-level names to jupyter_themes.egg-info\top_level.txt
        writing dependency_links to jupyter_themes.egg-info\dependency_links.txt
        writing entry points to jupyter_themes.egg-info\entry_points.txt
        warning: manifest_maker: standard file '-c' not found

        reading manifest file 'jupyter_themes.egg-info\SOURCES.txt'
        writing manifest file 'jupyter_themes.egg-info\SOURCES.txt'
        running build_ext
        Creating c:\anaconda\lib\site-packages\jupyter-themes.egg-link (link to .)
        jupyter-themes 0.1 is already the active version in easy-install.pth
        Installing jupyter-theme-script.py script to C:\Anaconda\Scripts
        Installing jupyter-theme.exe script to C:\Anaconda\Scripts

        Installed d:\projects\jupyter-themes
    Successfully installed jupyter-themes-0.1
    Cleaning up...

I haven't had a chance to figure out the cause yet (at first glance: check `__init__.py` which looks like it's using hardcoded Linux/Mac "~/" locations?) but the good news is that if we copy the css files correctly to the user directory ("C:\users\matt.trentini\.jupyter-themes" on my computer) then `jupyter-themes.exe` finds and lists them.

I think we're close...
