### ISSUE TITLE
cellw does not take percentage as input

### ISSUE THREAD

**Issue by Brian1Wang** [dunovank/jupyter-themes#70]
jt -t onedork -m 100 -T -N -cellw 100%
won't work as 100% is not an valid parameter

I need to manually search and replace the cellw value from 980px to 100% (.jupyter/custom/custom.css) to enable jupyter notebook to auto adjust its width based on the browser size.

It is an important and useful feature to have.

**Comment by ymost** [comment]
+1

**Comment by purplezigar** [comment]
This was the suggestion I posted a while ago. I definitely agree this would be extremely useful.

**Comment by dunovank** [comment]
Thanks for the feedback. The next release will have this functionality. Should be available within the next couple of days.

**Comment by dunovank** [comment]
@ymost @purplezigar @Brian1Wang 

install latest version (0.14.2):
`pip install --upgrade jupyterthemes`

then
`jt -t onedork -m 100 -T -N -cellw 100%`

should work now.

**Comment by ymost** [comment]
Awesome, thanks!
