### ISSUE TITLE
Fonts not working

### ISSUE THREAD

**Issue by brydavis** [dunovank/jupyter-themes#71]
If you don't have fonts installed on computer, then Jupyter can't upload fonts to use them. 

Suggestion: include fonts as part of package and `@font-face` them if not installed...

**Comment by purplezigar** [comment]
You might want to check on the `custom.css` file. The fonts were installed for me, but I needed to add an additional \ for the OS to recognize the file path for the fonts at the top of the file.

**Comment by pussinboot** [comment]
hi, custom fonts still not working for me
important to note that im on windows

**Comment by dunovank** [comment]
will be fixed in 0.14.3 (releasing shortly)
