### ISSUE TITLE
Cannot find custom.css file after install

### ISSUE THREAD

**Issue by JoshuaC3** [dunovank/jupyter-themes#72]
Since installing jupyter-themes I cannot control my jupyter notebook display settings via the custom.css file. Will this have moved as part of the install?

**Comment by purplezigar** [comment]
I don't think it should have moved. Where were you accessing it before installing?

**Comment by JoshuaC3** [comment]
I am almost certain that it moved. It is in `C:\Users\admin\.jupyter\custom` now whereas before it was in `C:\Users\admin\.ipython\profile_default\static\custom`.

I had some custom css e.g. `.container { width:90% !important; }` in `.ipython\...\custom.css` before install. After install and then using `jt -t _theme_` the custom css was unchanged. I then searched my c-drive for all `custom.css` and found the theme css in `.jupyter\...\custom.css`.

Is there an easier way to find the path for the `custom.css` the juypterthemes writes to?

**Comment by purplezigar** [comment]
Yeah it's supposed to have moved there. `.ipython` is the old directory, most people theme Jupyter in `.jupyter\...\custom.css`. If you want to change/add the .container (I do as well) just change it in `.jupyter\...\custom.css`. As for finding the path, I'm not sure what you mean. I would say backup your theme in the `.ipython` folder and just use the `.jupyter\...\custom.css`. That's what I've been doing and it works fine.

**Comment by JoshuaC3** [comment]
Thanks for clarifying.

So I have over 15 different `custom.css` files on my computer. There are some under ipython and jupyter and others in a separate directories (I think maybe where I accidentally installed jupyter outside of anaconda). Many of these are as a result of having different anaconda environments. Basically, it's all a bit messy.

What I would like to know is if there is a command that can be run, either in the notebook or command line that can locate the correct `custom.css`? Somehow `jt` "knows" where to look for each different environment.

Clearly this has caused others issues before [me](http://sherifsoliman.com/2016/01/11/theming-ipython-jupyter-notebook/)

**Comment by purplezigar** [comment]
My best guess would be to run `jupyter --config-dir` in the command line. I'm not really sure otherwise, I only have one instance of Jupyter on my machine.

**Comment by JoshuaC3** [comment]
Ran this and it gave `.jupyter`. So, yes it returns the correct folder for the config but then again, it think it returned this when it was using `.ipython/.../custom.css`, though I cannot be certain of this.

Thanks for your help.

Should I close or is it to be kept open as reference to the `custom.css` being moved?

**Comment by purplezigar** [comment]
You could also try running `ipython locate` to see where that folder is, but I'm not sure if it will help. Also from my understanding, Jupyter is installed in the root directory of your computer? When I run `jupyter --config-dir` I get `C:\Users\(my username)\.jupyter`. If you really care about this, you could uninstall every instance of Python and Anaconda and reinstall to have a fresh start. I did this a while back and it fixed most of my problems. If things are working and you don't want to mess with them, you could also leave it.

As for closing it, that's up to you. I don't really know how github works yet :/ .....

**Comment by JoshuaC3** [comment]
I will try `locate`. Thank you.

I cannot say I am but if think if the `custom.css` file moving as seen as a bug or as undesirable then keep it open. If it is intended or needed as part of jupyterthemes then close it.
