### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by BlakeTrebelhorn** [dunovank/jupyter-themes#73]
I've found 2 new issues.

On Windows at least, when the css file tries to find the fonts in fonts\\... it can't, because \ is an escape character (I think). I had to manually add another \ for the fonts to work.

When editing text files, the theme doesn't work quite well. The areas around the cell are still white. This is what I get: 
![2016-11-09 20_02_43-study md](https://cloud.githubusercontent.com/assets/18293448/20161974/8a5bc25c-a6b7-11e6-9aac-d9debe92a6a4.png)

**Comment by dunovank** [comment]
Both issues should be fixed in the latest version. Would anyone mind double checking that fonts are installable on Windows and that the text editor issue is resolved?

**Comment by dunovank** [comment]
Assuming this has been resolved
