### ISSUE TITLE
Mac OSX El Capitan, Chrome: Line for cursor width and color should end with !important

### ISSUE THREAD

**Issue by trondarild** [dunovank/jupyter-themes#74]
In the .jupyter/custom/custom.css file, this line:
`.cm-s-ipython .CodeMirror-cursor {                                                            
border-left: 3px solid #db797c;
 }
`

should be:
`
.cm-s-ipython .CodeMirror-cursor {                                                            
border-left: 3px solid #db797c !important;
 }
`
Otherwise, the cursor settings have no effect.

Thanks!

**Comment by beOn** [comment]
Came here to say the same thing.

**Comment by dunovank** [comment]
This should be fixed in the newest version.
