### ISSUE TITLE
Don't include fonts in package

### ISSUE THREAD

**Issue by acz13** [dunovank/jupyter-themes#75]
Let's be real. There are way to many fonts in here that are really just not needed.
``` bash
$ du -ch $(find . -name "*.*f")
[...]
14M	total

$ du -sh .
16M	.
```
(from within a conda package I built)

I suggest making another repository to contain the fonts and when the user wants them it will pull specific fonts from that directory...

**Comment by dunovank** [comment]
I'm not exactly opposed to this, and actually the more I think about it I'm more open to the idea. Would be nice to get more input from other users on removing the bulk of the fonts, maybe keep a few of the more popular monospace fonts? 

Let me think about it for a minute. Will update here if I end up removing (or re-packaging) the fonts.

Thanks for the input.
