### ISSUE TITLE
Layouts/Styles Missing from Tarball

### ISSUE THREAD

**Issue by llchan** [dunovank/jupyter-themes#78]
Not sure if I missed a memo about lazy fetching assets, but looks like the tarball releases don't contain the layouts/styles (fonts appear to be in there). Are they expected to be there?

**Comment by dunovank** [comment]
@llchan sorry for the super long delay. The latest release (v0.17.3) has been packaged with layouts and styles in the tarball.

Can upgrade with `pip install --upgrade jupyterthemes` 

Thanks!
