### ISSUE TITLE
Use StringIO

### ISSUE THREAD

**Issue by llchan** [dunovank/jupyter-themes#79]
The package directory is not necessarily writable by the user, so writing a hardcoded temp file in that directory doesnt always work. It's also not safe when multiple processes write at the same time.

One fix would be to use a proper tempfile (via the tempfile module). Better yet, lesscpy supports StringIO, so we should just do it in-memory. No reason to write to disk.

**Comment by dunovank** [comment]
Ah good point. I won't have time to get to this for a while. Always accepting PR's though :)
