### ISSUE TITLE
Cannot change font for code cells - keeps falling back to default droidmono

### ISSUE THREAD

**Issue by AlexArcPy** [dunovank/jupyter-themes#80]
I have Jupyter notebook  4.2.1 and am trying to change a font for the code cells.

Run this line in cmd on Windows:
`jt -t onedork -f consolamono -fs 13`

The theme has been applied. I can also see that the custom.css file (found at `C:\Users\user\.jupyter\custom`) has been updated:
```
@font-face {
 font-family: 'Consolamono';
 font-weight: normal;
 font-style: normal;
 src: local('Consolamono'), url('fonts\consolamono.ttf') format('truetype');
}
```

Can see that in the `C:\Users\user\.jupyter\custom\fonts` folder there is `consolamono.ttf` file. However, the code cell is using the `droidmono` font (have tested to use multiple other fonts with the same effect). It seems as it keeps falling back to the defaults. 

Changing the font for the markdown/text cells in notebook works fine, but not the code cells.

Where to look for possible fixes?

**Comment by WhistlingWanderer** [comment]
To solve the problem, you just have to manually replace the escape character in the font url by a directory separator (either `\\` or `/` on Windows). That is, in your case,
`url('fonts/consolamono.ttf')`
This seems to be a bug in the css generation process which simply hard-writes the path without correcting the separators.

**Comment by AlexArcPy** [comment]
@WhistlingWanderer , updating the paths to be 
`url('fonts/consolamono.ttf')`
fixed the problem, thanks a ton!
