### ISSUE TITLE
Set background image

### ISSUE THREAD

**Issue by ivalsar** [dunovank/jupyter-themes#81]
Hi!
Is it possible to set a background image to jupyter? That would be very nice..

**Comment by dunovank** [comment]
What did you have in mind? Like a watermark or image in the margin or like a large centered image in the background?

**Comment by linwoodc3** [comment]
I'm interested in setting the image like the examples on the main github page.  How do you do that?

**Comment by dunovank** [comment]
Hi, I'm not actually sure how to do this. Feel free to submit a PR with an optional argument for setting the background-image.
