### ISSUE TITLE
Math not displayed correctly

### ISSUE THREAD

**Issue by Findus23** [dunovank/jupyter-themes#93]
Hi,
I am using `jt -f firacode -t grade3` and it seems like there are errors displaying math with mathjax:
This 
```markdown
$$\pi["]=\frac{1pc}{d}$$
```
results into 
![bildschirmfoto vom 2017-01-24 10-47-24](https://cloud.githubusercontent.com/assets/6266037/22242137/8c9a9d30-e222-11e6-966b-4faf0bdd8ea0.png)
instead of 
![bildschirmfoto vom 2017-01-24 10-46-49](https://cloud.githubusercontent.com/assets/6266037/22242144/91ec3456-e222-11e6-8816-01fd18598a31.png)

Does it have to to with the following errors (which I also get when I am not using a theme):
![bildschirmfoto vom 2017-01-24 10-48-27](https://cloud.githubusercontent.com/assets/6266037/22242223/d430b24c-e222-11e6-91ea-8473c3cfd465.png)

**Comment by dunovank** [comment]
Is it fixed if you go to the jupyterthemes/layout/mathjax.css source code (presumably in your main site-packages directory) and comment out `preferredFont: "TeX",` as shown in line 20 of the screenshot?

![screenshot from 2017-02-24 12-54-55](https://cloud.githubusercontent.com/assets/3844814/23314789/62e4116a-fa91-11e6-9389-dd0447987b41.png)

If this works I'll go ahead and remove this line in the next release.

**Comment by dunovank** [comment]
Can anyone confirm that this has been fixed in the latest release?

**Comment by Findus23** [comment]
Sorry that I didn't respond earlier, to be honest I completely forgot.
I have updated to 
```ini
jupyter==1.0.0
jupyter-client==5.0.1
jupyter-console==5.1.0
jupyter-core==4.3.0
jupyterthemes==0.15.3
```
and ran `jt -f firacode -t grade3` again. Now the math is looking perfect again:
![screenshot_20170407_075405](https://cloud.githubusercontent.com/assets/6266037/24787216/6d55cf2a-1b67-11e7-9367-01d90d79bace.png)

Many thanks.

**Comment by dunovank** [comment]
No worries, glad it's fixed!
