### ISSUE TITLE
Have you seen the jupyter-themer project?

### ISSUE THREAD

**Issue by dtsmith2001** [dunovank/jupyter-themes#95]
Perhaps you could show how the two projects complement each other.

[https://github.com/transcranial/jupyter-themer](https://github.com/transcranial/jupyter-themer)

**Comment by dunovank** [comment]
I have seen this, it's much cleaner and more lightweight than jupyterthemes. The primary difference is that jupyterthemes uses Less to define all the user and theme settings as variables which then get compiled into the custom.css file using lesscpy. That way new themes are a little easier to develop (assuming you just want to alter the color scheme and not major changes to the layout, notebook formatting, etc..). You would just add a new .less file to jupyterthemes/styles/ directory, copy and paste all the variables from one of the other themes, and change the hexcodes to your liking. 

So, depending on who you ask, that's one benefit of jupyterthemes. But by the same token it's quite a bit messier, less straight forward than jupyter-themer... by a wide margin. Also, jupyterthemes includes code for customizing the layout of some pretty narrowly used features (i.e., nb-extensions page, command palette, etc.) so if you don't use those, then it's pretty obnoxious working around that code if you're trying to modify something in the source code. 

Finally, jupyter-themer has a ton more themes to choose from. I think going forward, it would be nice to have all (or most) of those syntax highlight themes available as jupyterthemes styles.

**Comment by hainm** [comment]
> Finally, jupyter-themer has a ton more themes to choose from. I

I think for general users, it would be best to just pick a theme from a small collection.
