### ISSUE TITLE
Can't set font size as a float

### ISSUE THREAD

**Issue by AllanLRH** [dunovank/jupyter-themes#99]
Can't set font size as a float, for instance `--monosize 8.5`.
Are it even allowed in CSS?

The entire command which I ran (probably not that useful): `jt --reset && jt --theme grade3 --monofont source --monosize 9 --hideprompt`

**Comment by dunovank** [comment]
you can set the font-size to a floating point by providing a three digit value 

`jt -t grade3 -fs 085 -f source`

will result in fontsize of 8.5pt
